// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user_vault

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	CreateUserVault(ctx context.Context, arg CreateUserVaultParams) error
	GetUserVault(ctx context.Context, userID uuid.UUID) (*models.UserVault, error)
	UpdateUserVaultPassword(ctx context.Context, arg UpdateUserVaultPasswordParams) error
}

var _ Querier = (*Queries)(nil)
