package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/sha1" //nolint:gosec // RFC 6238 needs HMAC-SHA1.
	"crypto/sha256"
	"encoding/base32"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/crypto/argon2"
	"golang.org/x/crypto/hkdf"
	"golang.org/x/text/unicode/norm"
)

// TestCrossLanguageVectors loads testdata/crypto-vectors.json (generated by
// cmd/genvectors) and verifies the Go implementation reproduces every entry
// byte-for-byte. The TS suite in frontend/packages/crypto/__tests__/vectors.test.ts
// runs the same checks against its WebCrypto/hash-wasm implementation, so
// any drift between the two languages is caught by either side.
func TestCrossLanguageVectors(t *testing.T) {
	v := loadVectors(t)

	t.Run("argon2id", func(t *testing.T) {
		for i, c := range v.Argon2ID {
			salt := mustHex(t, c.SaltHex)
			got := argon2.IDKey([]byte(c.Password), salt, c.T, c.MKiB, c.P, 32)
			if hex.EncodeToString(got) != c.HashHex {
				t.Fatalf("case %d: got %x want %s", i, got, c.HashHex)
			}
		}
	})

	t.Run("hkdf", func(t *testing.T) {
		for i, c := range v.HKDF {
			ikm := mustHex(t, c.IKMHex)
			salt := mustHex(t, c.SaltHex)
			r := hkdf.New(sha256.New, ikm, salt, []byte(c.Info))
			got := make([]byte, 32)
			if _, err := io.ReadFull(r, got); err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(got) != c.OutHex {
				t.Fatalf("case %d: got %x want %s", i, got, c.OutHex)
			}
		}
	})

	t.Run("aes_gcm", func(t *testing.T) {
		for i, c := range v.AESGCM {
			key := mustHex(t, c.KeyHex)
			nonce := mustHex(t, c.NonceHex)
			aad := mustHex(t, c.AADHex)
			pt := mustHex(t, c.PlaintextHex)
			ct := sealOrFatal(t, key, nonce, pt, aad)
			if hex.EncodeToString(ct) != c.CiphertextHex {
				t.Fatalf("case %d: got %x want %s", i, ct, c.CiphertextHex)
			}
			// Round-trip: open via the package under test using the full
			// envelope (version || nonce || ct+tag), so AESGCMOpen is
			// exercised on every vector.
			envelope := envWith(nonce, ct)
			out, err := AESGCMOpen(key, envelope, aad)
			if err != nil {
				t.Fatalf("case %d: open: %v", i, err)
			}
			if !bytesEqual(out, pt) {
				t.Fatalf("case %d: round-trip mismatch", i)
			}
		}
	})

	t.Run("verifier", func(t *testing.T) {
		for i, c := range v.Verifier {
			mk := mustHex(t, c.MasterKeyHex)
			nonce := mustHex(t, c.NonceHex)
			ct := sealOrFatal(t, mk, nonce, []byte("oblivio-verify"), []byte("vault-wrap"))
			env := envWith(nonce, ct)
			if hex.EncodeToString(env) != c.VerifierHex {
				t.Fatalf("case %d: verifier mismatch", i)
			}
		}
	})

	t.Run("blind_index", func(t *testing.T) {
		for i, c := range v.BlindIndex {
			vk := mustHex(t, c.VaultKeyHex)
			pepper := mustHex(t, c.PepperHex)
			r := hkdf.New(sha256.New, vk, pepper, []byte("oblivio/blind/v2"))
			k := make([]byte, 32)
			if _, err := io.ReadFull(r, k); err != nil {
				t.Fatal(err)
			}
			mac := hmac.New(sha256.New, k)
			mac.Write([]byte(strings.ToLower(norm.NFKC.String(c.Title))))
			got := mac.Sum(nil)
			if hex.EncodeToString(got) != c.HashHex {
				t.Fatalf("case %d title=%q: got %x want %s", i, c.Title, got, c.HashHex)
			}
		}
	})

	t.Run("totp_rfc6238", func(t *testing.T) {
		for i, c := range v.TOTPRFC6238 {
			secret, err := base32.StdEncoding.WithPadding(base32.NoPadding).DecodeString(c.SecretBase32)
			if err != nil {
				t.Fatal(err)
			}
			ctr := uint64(c.Unix / c.Period)
			got := generateHOTP(secret, ctr, c.Digits)
			if got != c.Code {
				t.Fatalf("case %d unix=%d: got %s want %s", i, c.Unix, got, c.Code)
			}
		}
	})

	t.Run("recovery_wrap", func(t *testing.T) {
		for i, c := range v.RecoveryWrap {
			salt := mustHex(t, c.SaltHex)
			nonce := mustHex(t, c.NonceHex)
			vault := mustHex(t, c.VaultKeyHex)
			recoveryKey := argon2.IDKey([]byte(normalizeRecoveryCode(c.RecoveryCode)), salt, 1, 1<<10, 1, 32)
			ct := sealOrFatal(t, recoveryKey, nonce, vault, []byte("recovery"))
			env := envWith(nonce, ct)
			if hex.EncodeToString(env) != c.WrappedHex {
				t.Fatalf("case %d: got %x want %s", i, env, c.WrappedHex)
			}
		}
	})

	t.Run("item_wrap", func(t *testing.T) {
		for i, c := range v.ItemWrap {
			vault := mustHex(t, c.VaultKeyHex)
			item := mustHex(t, c.ItemKeyHex)
			nonce := mustHex(t, c.NonceHex)
			aad := fmt.Sprintf("%s|%s|%d|wrap", c.VaultID, c.ItemID, c.Version)
			ct := sealOrFatal(t, vault, nonce, item, []byte(aad))
			env := envWith(nonce, ct)
			if hex.EncodeToString(env) != c.WrappedHex {
				t.Fatalf("case %d: got %x want %s", i, env, c.WrappedHex)
			}
		}
	})
}

// envWith reproduces the envelope layout the production code produces:
// version(1) || nonce(12) || ct+tag. Used by vector round-trip assertions.
func envWith(nonce, ct []byte) []byte {
	out := make([]byte, 0, 1+len(nonce)+len(ct))
	out = append(out, EnvelopeVersionV1)
	out = append(out, nonce...)
	out = append(out, ct...)
	return out
}

type vectorsFile struct {
	Argon2ID []struct {
		Password string `json:"password"`
		SaltHex  string `json:"salt_hex"`
		T        uint32 `json:"t"`
		MKiB     uint32 `json:"m_kib"`
		P        uint8  `json:"p"`
		HashHex  string `json:"hash_hex"`
	} `json:"argon2id"`
	HKDF []struct {
		IKMHex  string `json:"ikm_hex"`
		Info    string `json:"info"`
		SaltHex string `json:"salt_hex"`
		OutHex  string `json:"out_hex"`
	} `json:"hkdf"`
	AESGCM []struct {
		KeyHex        string `json:"key_hex"`
		NonceHex      string `json:"nonce_hex"`
		AADHex        string `json:"aad_hex"`
		PlaintextHex  string `json:"plaintext_hex"`
		CiphertextHex string `json:"ciphertext_hex"`
	} `json:"aes_gcm"`
	Verifier []struct {
		MasterKeyHex string `json:"master_key_hex"`
		NonceHex     string `json:"nonce_hex"`
		VerifierHex  string `json:"verifier_hex"`
	} `json:"verifier"`
	BlindIndex []struct {
		VaultKeyHex string `json:"vault_key_hex"`
		PepperHex   string `json:"pepper_hex"`
		Title       string `json:"title"`
		HashHex     string `json:"hash_hex"`
	} `json:"blind_index"`
	TOTPRFC6238 []struct {
		SecretBase32 string `json:"secret_b32"`
		Unix         int64  `json:"unix"`
		Period       int64  `json:"period"`
		Digits       int    `json:"digits"`
		Code         string `json:"code"`
	} `json:"totp_rfc6238"`
	RecoveryWrap []struct {
		RecoveryCode string `json:"recovery_code"`
		SaltHex      string `json:"salt_hex"`
		NonceHex     string `json:"nonce_hex"`
		VaultKeyHex  string `json:"vault_key_hex"`
		WrappedHex   string `json:"wrapped_hex"`
	} `json:"recovery_wrap"`
	ItemWrap []struct {
		VaultKeyHex string `json:"vault_key_hex"`
		ItemKeyHex  string `json:"item_key_hex"`
		NonceHex    string `json:"nonce_hex"`
		VaultID     string `json:"vault_id"`
		ItemID      string `json:"item_id"`
		Version     int64  `json:"version"`
		WrappedHex  string `json:"wrapped_hex"`
	} `json:"item_wrap"`
}

func loadVectors(t *testing.T) *vectorsFile {
	t.Helper()
	// Walk up from the test file's package until we find testdata/.
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for dir := wd; dir != "/" && dir != "."; dir = filepath.Dir(dir) {
		p := filepath.Join(dir, "testdata", "crypto-vectors.json")
		if _, err := os.Stat(p); err == nil {
			b, err := os.ReadFile(p)
			if err != nil {
				t.Fatal(err)
			}
			var v vectorsFile
			if err := json.Unmarshal(b, &v); err != nil {
				t.Fatal(err)
			}
			return &v
		}
	}
	t.Fatal("testdata/crypto-vectors.json not found")
	return nil
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func sealOrFatal(t *testing.T, key, nonce, pt, aad []byte) []byte {
	t.Helper()
	b, err := aes.NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	g, err := cipher.NewGCM(b)
	if err != nil {
		t.Fatal(err)
	}
	return g.Seal(nil, nonce, pt, aad)
}

func generateHOTP(secret []byte, counter uint64, digits int) string {
	var ctr [8]byte
	binary.BigEndian.PutUint64(ctr[:], counter)
	mac := hmac.New(sha1.New, secret)
	mac.Write(ctr[:])
	sum := mac.Sum(nil)
	off := sum[len(sum)-1] & 0x0f
	v := (uint32(sum[off]&0x7f) << 24) |
		(uint32(sum[off+1]&0xff) << 16) |
		(uint32(sum[off+2]&0xff) << 8) |
		uint32(sum[off+3]&0xff)
	mod := uint32(1)
	for range digits {
		mod *= 10
	}
	v %= mod
	return fmt.Sprintf("%0*d", digits, v)
}

func normalizeRecoveryCode(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '-' || c == ' ' {
			continue
		}
		if c >= 'a' && c <= 'z' {
			c -= 32
		}
		out = append(out, c)
	}
	return string(out)
}

func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
