// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user_auth

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	GetUserAuth(ctx context.Context, userID uuid.UUID) (*models.UserAuth, error)
	RecordFailedLogin(ctx context.Context, userID uuid.UUID) (*RecordFailedLoginRow, error)
	ResetFailedLogin(ctx context.Context, userID uuid.UUID) error
	UpsertUserAuth(ctx context.Context, arg UpsertUserAuthParams) error
}

var _ Querier = (*Queries)(nil)
