// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_auth.sql

package user_auth

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const getUserAuth = `-- name: GetUserAuth :one
SELECT user_id, auth_key_hash, failed_attempts, locked_until FROM user_auth WHERE user_id = $1
`

func (q *Queries) GetUserAuth(ctx context.Context, userID uuid.UUID) (*models.UserAuth, error) {
	row := q.db.QueryRow(ctx, getUserAuth, userID)
	var i models.UserAuth
	err := row.Scan(
		&i.UserID,
		&i.AuthKeyHash,
		&i.FailedAttempts,
		&i.LockedUntil,
	)
	return &i, err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE user_auth
SET failed_attempts = failed_attempts + 1,
    locked_until    = CASE
        WHEN failed_attempts + 1 >= 5 THEN now() + interval '15 minutes'
        ELSE locked_until
    END
WHERE user_id = $1
RETURNING failed_attempts, locked_until
`

type RecordFailedLoginRow struct {
	FailedAttempts int32              `db:"failed_attempts" json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
}

func (q *Queries) RecordFailedLogin(ctx context.Context, userID uuid.UUID) (*RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, userID)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return &i, err
}

const resetFailedLogin = `-- name: ResetFailedLogin :exec
UPDATE user_auth
SET failed_attempts = 0,
    locked_until    = NULL
WHERE user_id = $1
`

func (q *Queries) ResetFailedLogin(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLogin, userID)
	return err
}

const upsertUserAuth = `-- name: UpsertUserAuth :exec
INSERT INTO user_auth (user_id, auth_key_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET auth_key_hash   = EXCLUDED.auth_key_hash,
    failed_attempts = 0,
    locked_until    = NULL
`

type UpsertUserAuthParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	AuthKeyHash string    `db:"auth_key_hash" json:"auth_key_hash"`
}

func (q *Queries) UpsertUserAuth(ctx context.Context, arg UpsertUserAuthParams) error {
	_, err := q.db.Exec(ctx, upsertUserAuth, arg.UserID, arg.AuthKeyHash)
	return err
}
