// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limit_buckets.sql

package repo_rate_limit_buckets

import (
	"context"
)

const consumeRateLimit = `-- name: ConsumeRateLimit :one

INSERT INTO rate_limit_buckets (kind, key, tokens, refilled_at)
VALUES (
    $1::text,
    $2::text,
    $3::double precision - 1,
    now()
)
ON CONFLICT (kind, key) DO UPDATE
SET tokens = LEAST(
        $3::double precision,
        rate_limit_buckets.tokens
            + $4::double precision
                * GREATEST(0, EXTRACT(EPOCH FROM (now() - rate_limit_buckets.refilled_at)))
    ) - 1,
    refilled_at = now()
RETURNING tokens
`

type ConsumeRateLimitParams struct {
	Kind       string  `db:"kind" json:"kind"`
	Key        string  `db:"key" json:"key"`
	Burst      float64 `db:"burst" json:"burst"`
	RatePerSec float64 `db:"rate_per_sec" json:"rate_per_sec"`
}

// Atomic refill-and-consume in one statement. The CTE computes the new
// token count from the existing row (or starts at $4=burst-1 for a fresh
// bucket) and writes it back, RETURNING the resulting `tokens` value so
// the caller can decide allow/deny by checking >= 0.
//
// Refill rate is `rate_per_sec` tokens per second; cap at $4 (burst).
// We let `tokens` go briefly negative to indicate "denied this request"
// without a separate rejection path — the Go code clamps to 0 on the
// next allow.
func (q *Queries) ConsumeRateLimit(ctx context.Context, arg ConsumeRateLimitParams) (float64, error) {
	row := q.db.QueryRow(ctx, consumeRateLimit,
		arg.Kind,
		arg.Key,
		arg.Burst,
		arg.RatePerSec,
	)
	var tokens float64
	err := row.Scan(&tokens)
	return tokens, err
}

const deleteStaleRateLimitBuckets = `-- name: DeleteStaleRateLimitBuckets :execrows
DELETE FROM rate_limit_buckets
WHERE refilled_at < now() - INTERVAL '1 hour'
`

// Reaps buckets that are full (tokens >= burst-1) and untouched for >1h.
// Buckets that are actively in use refresh their refilled_at and stay.
func (q *Queries) DeleteStaleRateLimitBuckets(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleRateLimitBuckets)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
