// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limit_buckets.sql

package repo_rate_limit_buckets

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const deleteStaleBuckets = `-- name: DeleteStaleBuckets :execrows
DELETE FROM rate_limit_buckets WHERE last_refill_at < $1
`

func (q *Queries) DeleteStaleBuckets(ctx context.Context, lastRefillAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleBuckets, lastRefillAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBucket = `-- name: GetBucket :one
SELECT bucket_key, tokens, last_refill_at FROM rate_limit_buckets WHERE bucket_key = $1
`

func (q *Queries) GetBucket(ctx context.Context, bucketKey string) (*models.RateLimitBucket, error) {
	row := q.db.QueryRow(ctx, getBucket, bucketKey)
	var i models.RateLimitBucket
	err := row.Scan(&i.BucketKey, &i.Tokens, &i.LastRefillAt)
	return &i, err
}

const upsertBucket = `-- name: UpsertBucket :exec
INSERT INTO rate_limit_buckets (bucket_key, tokens, last_refill_at)
VALUES ($1, $2, $3)
ON CONFLICT (bucket_key) DO UPDATE
SET tokens = EXCLUDED.tokens, last_refill_at = EXCLUDED.last_refill_at
`

type UpsertBucketParams struct {
	BucketKey    string             `db:"bucket_key" json:"bucket_key"`
	Tokens       float32            `db:"tokens" json:"tokens"`
	LastRefillAt pgtype.Timestamptz `db:"last_refill_at" json:"last_refill_at"`
}

func (q *Queries) UpsertBucket(ctx context.Context, arg UpsertBucketParams) error {
	_, err := q.db.Exec(ctx, upsertBucket, arg.BucketKey, arg.Tokens, arg.LastRefillAt)
	return err
}
