// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package repo_idempotency_keys

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const deleteExpiredIdempotencyEntries = `-- name: DeleteExpiredIdempotencyEntries :execrows
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyEntries(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyEntries)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyEntry = `-- name: GetIdempotencyEntry :one
SELECT key, user_id, procedure, request_hash, response_status, response_body, created_at, expires_at FROM idempotency_keys
WHERE user_id = $1 AND key = $2 AND expires_at > now()
`

type GetIdempotencyEntryParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Key    string    `db:"key" json:"key"`
}

func (q *Queries) GetIdempotencyEntry(ctx context.Context, arg GetIdempotencyEntryParams) (*models.IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyEntry, arg.UserID, arg.Key)
	var i models.IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.Procedure,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const insertIdempotencyEntry = `-- name: InsertIdempotencyEntry :exec
INSERT INTO idempotency_keys (
    user_id, key, procedure, request_hash,
    response_status, response_body, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIdempotencyEntryParams struct {
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Key            string             `db:"key" json:"key"`
	Procedure      string             `db:"procedure" json:"procedure"`
	RequestHash    []byte             `db:"request_hash" json:"request_hash"`
	ResponseStatus int32              `db:"response_status" json:"response_status"`
	ResponseBody   []byte             `db:"response_body" json:"response_body"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertIdempotencyEntry(ctx context.Context, arg InsertIdempotencyEntryParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyEntry,
		arg.UserID,
		arg.Key,
		arg.Procedure,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	return err
}
