// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package auth_sessions

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const getSessionByAccessHash = `-- name: GetSessionByAccessHash :one
SELECT id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at FROM auth_sessions
WHERE access_token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSessionByAccessHash(ctx context.Context, accessTokenHash []byte) (*models.AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByAccessHash, accessTokenHash)
	var i models.AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.Ip,
		&i.Country,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return &i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at FROM auth_sessions WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (*models.AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i models.AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.Ip,
		&i.Country,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return &i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at FROM auth_sessions
WHERE refresh_token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (*models.AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i models.AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.Ip,
		&i.Country,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return &i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at FROM auth_sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]*models.AuthSession, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.AuthSession{}
	for rows.Next() {
		var i models.AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceName,
			&i.Ip,
			&i.Country,
			&i.AccessTokenHash,
			&i.RefreshTokenHash,
			&i.AccessExpiresAt,
			&i.RefreshExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE auth_sessions
SET access_token_hash  = $2,
    refresh_token_hash = $3,
    access_expires_at  = $4,
    refresh_expires_at = $5,
    last_seen_at       = now()
WHERE id = $1
`

type RotateSessionParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	AccessTokenHash  []byte             `db:"access_token_hash" json:"access_token_hash"`
	RefreshTokenHash []byte             `db:"refresh_token_hash" json:"refresh_token_hash"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at" json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at" json:"refresh_expires_at"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession,
		arg.ID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO auth_sessions (
    user_id, device_id, device_type, device_name,
    ip, country,
    access_token_hash, refresh_token_hash,
    access_expires_at, refresh_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, device_id) DO UPDATE
SET device_type        = EXCLUDED.device_type,
    device_name        = EXCLUDED.device_name,
    ip                 = EXCLUDED.ip,
    country            = EXCLUDED.country,
    access_token_hash  = EXCLUDED.access_token_hash,
    refresh_token_hash = EXCLUDED.refresh_token_hash,
    access_expires_at  = EXCLUDED.access_expires_at,
    refresh_expires_at = EXCLUDED.refresh_expires_at,
    revoked_at         = NULL,
    last_seen_at       = now()
RETURNING id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at
`

type UpsertSessionParams struct {
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID         string             `db:"device_id" json:"device_id"`
	DeviceType       string             `db:"device_type" json:"device_type"`
	DeviceName       pgtype.Text        `db:"device_name" json:"device_name"`
	Ip               *netip.Addr        `db:"ip" json:"ip"`
	Country          pgtype.Text        `db:"country" json:"country"`
	AccessTokenHash  []byte             `db:"access_token_hash" json:"access_token_hash"`
	RefreshTokenHash []byte             `db:"refresh_token_hash" json:"refresh_token_hash"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at" json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at" json:"refresh_expires_at"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (*models.AuthSession, error) {
	row := q.db.QueryRow(ctx, upsertSession,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceType,
		arg.DeviceName,
		arg.Ip,
		arg.Country,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i models.AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.Ip,
		&i.Country,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return &i, err
}
