// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auth_sessions

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	GetSessionByAccessHash(ctx context.Context, accessTokenHash []byte) (*models.AuthSession, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (*models.AuthSession, error)
	GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (*models.AuthSession, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]*models.AuthSession, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RotateSession(ctx context.Context, arg RotateSessionParams) error
	UpsertSession(ctx context.Context, arg UpsertSessionParams) (*models.AuthSession, error)
}

var _ Querier = (*Queries)(nil)
