// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_sessions.sql

package repo_recovery_sessions

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const deleteExpiredRecoverySessions = `-- name: DeleteExpiredRecoverySessions :execrows
DELETE FROM recovery_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredRecoverySessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRecoverySessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoverySession = `-- name: DeleteRecoverySession :execrows
DELETE FROM recovery_sessions WHERE id = $1
`

func (q *Queries) DeleteRecoverySession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecoverySession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecoverySession = `-- name: GetRecoverySession :one
SELECT id, user_id, email, expires_at FROM recovery_sessions WHERE id = $1
`

func (q *Queries) GetRecoverySession(ctx context.Context, id uuid.UUID) (*models.RecoverySession, error) {
	row := q.db.QueryRow(ctx, getRecoverySession, id)
	var i models.RecoverySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
	)
	return &i, err
}

const insertRecoverySession = `-- name: InsertRecoverySession :one
INSERT INTO recovery_sessions (id, user_id, email, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertRecoverySessionParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertRecoverySession(ctx context.Context, arg InsertRecoverySessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRecoverySession,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const takeRecoverySession = `-- name: TakeRecoverySession :one
DELETE FROM recovery_sessions
WHERE id = $1
RETURNING id, user_id, email, expires_at
`

func (q *Queries) TakeRecoverySession(ctx context.Context, id uuid.UUID) (*models.RecoverySession, error) {
	row := q.db.QueryRow(ctx, takeRecoverySession, id)
	var i models.RecoverySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
	)
	return &i, err
}
