// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user_login_totp

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	DeleteUserLoginTOTP(ctx context.Context, userID uuid.UUID) error
	GetUserLoginTOTP(ctx context.Context, userID uuid.UUID) (*models.UserLoginTotp, error)
	UpsertUserLoginTOTP(ctx context.Context, arg UpsertUserLoginTOTPParams) error
}

var _ Querier = (*Queries)(nil)
