// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_login_totp.sql

package user_login_totp

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

const deleteUserLoginTOTP = `-- name: DeleteUserLoginTOTP :exec
DELETE FROM user_login_totp WHERE user_id = $1
`

func (q *Queries) DeleteUserLoginTOTP(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserLoginTOTP, userID)
	return err
}

const getUserLoginTOTP = `-- name: GetUserLoginTOTP :one
SELECT user_id, encrypted_secret, nonce, enabled, created_at FROM user_login_totp WHERE user_id = $1
`

func (q *Queries) GetUserLoginTOTP(ctx context.Context, userID uuid.UUID) (*models.UserLoginTotp, error) {
	row := q.db.QueryRow(ctx, getUserLoginTOTP, userID)
	var i models.UserLoginTotp
	err := row.Scan(
		&i.UserID,
		&i.EncryptedSecret,
		&i.Nonce,
		&i.Enabled,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertUserLoginTOTP = `-- name: UpsertUserLoginTOTP :exec
INSERT INTO user_login_totp (user_id, encrypted_secret, nonce, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET encrypted_secret = EXCLUDED.encrypted_secret,
    nonce            = EXCLUDED.nonce,
    enabled          = EXCLUDED.enabled
`

type UpsertUserLoginTOTPParams struct {
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	EncryptedSecret []byte    `db:"encrypted_secret" json:"encrypted_secret"`
	Nonce           []byte    `db:"nonce" json:"nonce"`
	Enabled         bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpsertUserLoginTOTP(ctx context.Context, arg UpsertUserLoginTOTPParams) error {
	_, err := q.db.Exec(ctx, upsertUserLoginTOTP,
		arg.UserID,
		arg.EncryptedSecret,
		arg.Nonce,
		arg.Enabled,
	)
	return err
}
