// Code generated by pgxgen. DO NOT EDIT.
package delegation_orders

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameDelegationOrders TableName = "delegation_orders"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameDelegationOrdersId              ColumnName = "id"
	ColumnNameDelegationOrdersWalletId        ColumnName = "wallet_id"
	ColumnNameDelegationOrdersTargetAddress   ColumnName = "target_address"
	ColumnNameDelegationOrdersResourceType    ColumnName = "resource_type"
	ColumnNameDelegationOrdersAmount          ColumnName = "amount"
	ColumnNameDelegationOrdersPeriod          ColumnName = "period"
	ColumnNameDelegationOrdersStatus          ColumnName = "status"
	ColumnNameDelegationOrdersProvider        ColumnName = "provider"
	ColumnNameDelegationOrdersProviderOrderId ColumnName = "provider_order_id"
	ColumnNameDelegationOrdersErrorMessage    ColumnName = "error_message"
	ColumnNameDelegationOrdersIsManual        ColumnName = "is_manual"
	ColumnNameDelegationOrdersCreatedAt       ColumnName = "created_at"
	ColumnNameDelegationOrdersUpdatedAt       ColumnName = "updated_at"
	ColumnNameDelegationOrdersCostTrx         ColumnName = "cost_trx"
	ColumnNameDelegationOrdersTxHash          ColumnName = "tx_hash"
	ColumnNameDelegationOrdersDeliveredAmount ColumnName = "delivered_amount"
)

func DelegationOrdersColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameDelegationOrdersId,
		ColumnNameDelegationOrdersWalletId,
		ColumnNameDelegationOrdersTargetAddress,
		ColumnNameDelegationOrdersResourceType,
		ColumnNameDelegationOrdersAmount,
		ColumnNameDelegationOrdersPeriod,
		ColumnNameDelegationOrdersStatus,
		ColumnNameDelegationOrdersProvider,
		ColumnNameDelegationOrdersProviderOrderId,
		ColumnNameDelegationOrdersErrorMessage,
		ColumnNameDelegationOrdersIsManual,
		ColumnNameDelegationOrdersCreatedAt,
		ColumnNameDelegationOrdersUpdatedAt,
		ColumnNameDelegationOrdersCostTrx,
		ColumnNameDelegationOrdersTxHash,
		ColumnNameDelegationOrdersDeliveredAmount,
	}
}
