// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegation_orders_extra.sql

package delegation_orders

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const finalizePendingOrder = `-- name: FinalizePendingOrder :one
UPDATE delegation_orders
SET status = $1,
    error_message = $2,
    cost_trx = COALESCE($3, cost_trx),
    tx_hash = COALESCE($4, tx_hash),
    delivered_amount = COALESCE($5, delivered_amount),
    updated_at = now()
WHERE id = $6
RETURNING id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount
`

type FinalizePendingOrderParams struct {
	Status          models.DelegationStatus `db:"status" json:"status"`
	ErrorMessage    pgtype.Text             `db:"error_message" json:"error_message"`
	CostTrx         pgtype.Numeric          `db:"cost_trx" json:"cost_trx"`
	TxHash          pgtype.Text             `db:"tx_hash" json:"tx_hash"`
	DeliveredAmount pgtype.Int8             `db:"delivered_amount" json:"delivered_amount"`
	ID              uuid.UUID               `db:"id" json:"id"`
}

func (q *Queries) FinalizePendingOrder(ctx context.Context, arg FinalizePendingOrderParams) (*models.DelegationOrder, error) {
	row := q.db.QueryRow(ctx, finalizePendingOrder,
		arg.Status,
		arg.ErrorMessage,
		arg.CostTrx,
		arg.TxHash,
		arg.DeliveredAmount,
		arg.ID,
	)
	var i models.DelegationOrder
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TargetAddress,
		&i.ResourceType,
		&i.Amount,
		&i.Period,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ErrorMessage,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostTrx,
		&i.TxHash,
		&i.DeliveredAmount,
	)
	return &i, err
}

const listPendingProviderOrders = `-- name: ListPendingProviderOrders :many
SELECT id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount
FROM delegation_orders
WHERE status = 'processing'
  AND tx_hash IS NULL
  AND provider = $1
  AND created_at > now() - $2::interval
ORDER BY created_at ASC
`

type ListPendingProviderOrdersParams struct {
	Provider string          `db:"provider" json:"provider"`
	Column2  pgtype.Interval `db:"column_2" json:"column_2"`
}

func (q *Queries) ListPendingProviderOrders(ctx context.Context, arg ListPendingProviderOrdersParams) ([]*models.DelegationOrder, error) {
	rows, err := q.db.Query(ctx, listPendingProviderOrders, arg.Provider, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.DelegationOrder{}
	for rows.Next() {
		var i models.DelegationOrder
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TargetAddress,
			&i.ResourceType,
			&i.Amount,
			&i.Period,
			&i.Status,
			&i.Provider,
			&i.ProviderOrderID,
			&i.ErrorMessage,
			&i.IsManual,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CostTrx,
			&i.TxHash,
			&i.DeliveredAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const timeoutStalePendingOrders = `-- name: TimeoutStalePendingOrders :exec
UPDATE delegation_orders
SET status = 'failed',
    error_message = 'polling timeout',
    updated_at = now()
WHERE status = 'processing'
  AND tx_hash IS NULL
  AND provider = $1
  AND created_at <= now() - $2::interval
`

type TimeoutStalePendingOrdersParams struct {
	Provider string          `db:"provider" json:"provider"`
	Column2  pgtype.Interval `db:"column_2" json:"column_2"`
}

func (q *Queries) TimeoutStalePendingOrders(ctx context.Context, arg TimeoutStalePendingOrdersParams) error {
	_, err := q.db.Exec(ctx, timeoutStalePendingOrders, arg.Provider, arg.Column2)
	return err
}

const updateDelegationOrderResult = `-- name: UpdateDelegationOrderResult :one
UPDATE delegation_orders
SET status = $1,
    provider = $2,
    provider_order_id = $3,
    error_message = $4,
    cost_trx = $5,
    tx_hash = $6,
    delivered_amount = $7,
    updated_at = now()
WHERE id = $8
RETURNING id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount
`

type UpdateDelegationOrderResultParams struct {
	Status          models.DelegationStatus `db:"status" json:"status"`
	Provider        string                  `db:"provider" json:"provider"`
	ProviderOrderID pgtype.Text             `db:"provider_order_id" json:"provider_order_id"`
	ErrorMessage    pgtype.Text             `db:"error_message" json:"error_message"`
	CostTrx         pgtype.Numeric          `db:"cost_trx" json:"cost_trx"`
	TxHash          pgtype.Text             `db:"tx_hash" json:"tx_hash"`
	DeliveredAmount pgtype.Int8             `db:"delivered_amount" json:"delivered_amount"`
	ID              uuid.UUID               `db:"id" json:"id"`
}

func (q *Queries) UpdateDelegationOrderResult(ctx context.Context, arg UpdateDelegationOrderResultParams) (*models.DelegationOrder, error) {
	row := q.db.QueryRow(ctx, updateDelegationOrderResult,
		arg.Status,
		arg.Provider,
		arg.ProviderOrderID,
		arg.ErrorMessage,
		arg.CostTrx,
		arg.TxHash,
		arg.DeliveredAmount,
		arg.ID,
	)
	var i models.DelegationOrder
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TargetAddress,
		&i.ResourceType,
		&i.Amount,
		&i.Period,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ErrorMessage,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostTrx,
		&i.TxHash,
		&i.DeliveredAmount,
	)
	return &i, err
}

const updateDelegationOrderStatus = `-- name: UpdateDelegationOrderStatus :one
UPDATE delegation_orders
SET status = $2, provider_order_id = $3, error_message = $4, updated_at = now()
WHERE id = $1
RETURNING id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount
`

type UpdateDelegationOrderStatusParams struct {
	ID              uuid.UUID               `db:"id" json:"id"`
	Status          models.DelegationStatus `db:"status" json:"status"`
	ProviderOrderID pgtype.Text             `db:"provider_order_id" json:"provider_order_id"`
	ErrorMessage    pgtype.Text             `db:"error_message" json:"error_message"`
}

func (q *Queries) UpdateDelegationOrderStatus(ctx context.Context, arg UpdateDelegationOrderStatusParams) (*models.DelegationOrder, error) {
	row := q.db.QueryRow(ctx, updateDelegationOrderStatus,
		arg.ID,
		arg.Status,
		arg.ProviderOrderID,
		arg.ErrorMessage,
	)
	var i models.DelegationOrder
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TargetAddress,
		&i.ResourceType,
		&i.Amount,
		&i.Period,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ErrorMessage,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostTrx,
		&i.TxHash,
		&i.DeliveredAmount,
	)
	return &i, err
}
