// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegation_orders_gen.sql

package delegation_orders

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const create = `-- name: Create :one
INSERT INTO delegation_orders (wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, cost_trx, tx_hash, delivered_amount)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), $11, $12, $13)
	RETURNING id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount
`

type CreateParams struct {
	WalletID        uuid.NullUUID                 `db:"wallet_id" json:"wallet_id"`
	TargetAddress   string                        `db:"target_address" json:"target_address"`
	ResourceType    models.DelegationResourceType `db:"resource_type" json:"resource_type"`
	Amount          int64                         `db:"amount" json:"amount"`
	Period          string                        `db:"period" json:"period"`
	Status          models.DelegationStatus       `db:"status" json:"status"`
	Provider        string                        `db:"provider" json:"provider"`
	ProviderOrderID pgtype.Text                   `db:"provider_order_id" json:"provider_order_id"`
	ErrorMessage    pgtype.Text                   `db:"error_message" json:"error_message"`
	IsManual        bool                          `db:"is_manual" json:"is_manual"`
	CostTrx         pgtype.Numeric                `db:"cost_trx" json:"cost_trx"`
	TxHash          pgtype.Text                   `db:"tx_hash" json:"tx_hash"`
	DeliveredAmount pgtype.Int8                   `db:"delivered_amount" json:"delivered_amount"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.DelegationOrder, error) {
	row := q.db.QueryRow(ctx, create,
		arg.WalletID,
		arg.TargetAddress,
		arg.ResourceType,
		arg.Amount,
		arg.Period,
		arg.Status,
		arg.Provider,
		arg.ProviderOrderID,
		arg.ErrorMessage,
		arg.IsManual,
		arg.CostTrx,
		arg.TxHash,
		arg.DeliveredAmount,
	)
	var i models.DelegationOrder
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TargetAddress,
		&i.ResourceType,
		&i.Amount,
		&i.Period,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ErrorMessage,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostTrx,
		&i.TxHash,
		&i.DeliveredAmount,
	)
	return &i, err
}

const find = `-- name: Find :many
SELECT id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount FROM delegation_orders ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type FindParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) Find(ctx context.Context, arg FindParams) ([]*models.DelegationOrder, error) {
	rows, err := q.db.Query(ctx, find, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.DelegationOrder{}
	for rows.Next() {
		var i models.DelegationOrder
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TargetAddress,
			&i.ResourceType,
			&i.Amount,
			&i.Period,
			&i.Status,
			&i.Provider,
			&i.ProviderOrderID,
			&i.ErrorMessage,
			&i.IsManual,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CostTrx,
			&i.TxHash,
			&i.DeliveredAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount FROM delegation_orders WHERE id=$1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.DelegationOrder, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.DelegationOrder
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TargetAddress,
		&i.ResourceType,
		&i.Amount,
		&i.Period,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ErrorMessage,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostTrx,
		&i.TxHash,
		&i.DeliveredAmount,
	)
	return &i, err
}

const total = `-- name: Total :one
SELECT count(1) as total FROM delegation_orders
`

func (q *Queries) Total(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, total)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const update = `-- name: Update :one
UPDATE delegation_orders
	SET wallet_id=$1, target_address=$2, resource_type=$3, amount=$4, period=$5, status=$6, provider=$7, provider_order_id=$8, error_message=$9, is_manual=$10, updated_at=now(), cost_trx=$11, tx_hash=$12, delivered_amount=$13
WHERE id=$14
	RETURNING id, wallet_id, target_address, resource_type, amount, period, status, provider, provider_order_id, error_message, is_manual, created_at, updated_at, cost_trx, tx_hash, delivered_amount
`

type UpdateParams struct {
	WalletID        uuid.NullUUID                 `db:"wallet_id" json:"wallet_id"`
	TargetAddress   string                        `db:"target_address" json:"target_address"`
	ResourceType    models.DelegationResourceType `db:"resource_type" json:"resource_type"`
	Amount          int64                         `db:"amount" json:"amount"`
	Period          string                        `db:"period" json:"period"`
	Status          models.DelegationStatus       `db:"status" json:"status"`
	Provider        string                        `db:"provider" json:"provider"`
	ProviderOrderID pgtype.Text                   `db:"provider_order_id" json:"provider_order_id"`
	ErrorMessage    pgtype.Text                   `db:"error_message" json:"error_message"`
	IsManual        bool                          `db:"is_manual" json:"is_manual"`
	CostTrx         pgtype.Numeric                `db:"cost_trx" json:"cost_trx"`
	TxHash          pgtype.Text                   `db:"tx_hash" json:"tx_hash"`
	DeliveredAmount pgtype.Int8                   `db:"delivered_amount" json:"delivered_amount"`
	ID              uuid.UUID                     `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.DelegationOrder, error) {
	row := q.db.QueryRow(ctx, update,
		arg.WalletID,
		arg.TargetAddress,
		arg.ResourceType,
		arg.Amount,
		arg.Period,
		arg.Status,
		arg.Provider,
		arg.ProviderOrderID,
		arg.ErrorMessage,
		arg.IsManual,
		arg.CostTrx,
		arg.TxHash,
		arg.DeliveredAmount,
		arg.ID,
	)
	var i models.DelegationOrder
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TargetAddress,
		&i.ResourceType,
		&i.Amount,
		&i.Period,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ErrorMessage,
		&i.IsManual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CostTrx,
		&i.TxHash,
		&i.DeliveredAmount,
	)
	return &i, err
}
