// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package delegation_orders

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.DelegationOrder, error)
	FinalizePendingOrder(ctx context.Context, arg FinalizePendingOrderParams) (*models.DelegationOrder, error)
	Find(ctx context.Context, arg FindParams) ([]*models.DelegationOrder, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.DelegationOrder, error)
	ListPendingProviderOrders(ctx context.Context, arg ListPendingProviderOrdersParams) ([]*models.DelegationOrder, error)
	TimeoutStalePendingOrders(ctx context.Context, arg TimeoutStalePendingOrdersParams) error
	Total(ctx context.Context) (int64, error)
	Update(ctx context.Context, arg UpdateParams) (*models.DelegationOrder, error)
	UpdateDelegationOrderResult(ctx context.Context, arg UpdateDelegationOrderResultParams) (*models.DelegationOrder, error)
	UpdateDelegationOrderStatus(ctx context.Context, arg UpdateDelegationOrderStatusParams) (*models.DelegationOrder, error)
}

var _ Querier = (*Queries)(nil)
