// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package repo_auth_sessions

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM auth_sessions
WHERE refresh_expires_at < $1
   OR (revoked_at IS NOT NULL AND revoked_at < $1)
`

// Reaps rows whose refresh has expired or that have been revoked far enough
// in the past that the audit chain already captured the termination event.
// Keeping revoked rows around briefly lets "I just logged out from the other
// tab" investigations succeed; 24h is long enough for that.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, refreshExpiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, refreshExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, current_refresh_key, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at FROM auth_sessions WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (*models.AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i models.AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.Ip,
		&i.Country,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.CurrentRefreshKey,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return &i, err
}

const getSessionCurrentRefreshKey = `-- name: GetSessionCurrentRefreshKey :one
SELECT current_refresh_key FROM auth_sessions WHERE id = $1
`

func (q *Queries) GetSessionCurrentRefreshKey(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSessionCurrentRefreshKey, id)
	var current_refresh_key []byte
	err := row.Scan(&current_refresh_key)
	return current_refresh_key, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, current_refresh_key, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at FROM auth_sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]*models.AuthSession, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.AuthSession{}
	for rows.Next() {
		var i models.AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceName,
			&i.Ip,
			&i.Country,
			&i.AccessTokenHash,
			&i.RefreshTokenHash,
			&i.CurrentRefreshKey,
			&i.AccessExpiresAt,
			&i.RefreshExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeAllUserSessionsExcept = `-- name: RevokeAllUserSessionsExcept :execrows
UPDATE auth_sessions SET revoked_at = now()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeAllUserSessionsExceptParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) RevokeAllUserSessionsExcept(ctx context.Context, arg RevokeAllUserSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessionsExcept, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const setSessionCurrentRefreshKey = `-- name: SetSessionCurrentRefreshKey :exec
UPDATE auth_sessions
SET current_refresh_key = $2,
    last_seen_at        = now()
WHERE id = $1
`

type SetSessionCurrentRefreshKeyParams struct {
	ID                uuid.UUID `db:"id" json:"id"`
	CurrentRefreshKey []byte    `db:"current_refresh_key" json:"current_refresh_key"`
}

func (q *Queries) SetSessionCurrentRefreshKey(ctx context.Context, arg SetSessionCurrentRefreshKeyParams) error {
	_, err := q.db.Exec(ctx, setSessionCurrentRefreshKey, arg.ID, arg.CurrentRefreshKey)
	return err
}

const touchSession = `-- name: TouchSession :exec

UPDATE auth_sessions SET last_seen_at = now() WHERE id = $1
`

// The legacy GetSessionByAccessHash / GetSessionByRefreshHash queries were
// removed: the auth_tokens table is now the source of truth for token
// validity, and auth_sessions.{access,refresh}_token_hash are no longer
// written.
// Drives the "recently active" UI sort.
func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO auth_sessions (
    user_id, device_id, device_type, device_name,
    ip, country,
    access_expires_at, refresh_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, device_id) DO UPDATE
SET device_type        = EXCLUDED.device_type,
    device_name        = EXCLUDED.device_name,
    ip                 = EXCLUDED.ip,
    country            = EXCLUDED.country,
    access_expires_at  = EXCLUDED.access_expires_at,
    refresh_expires_at = EXCLUDED.refresh_expires_at,
    revoked_at         = NULL,
    last_seen_at       = now()
RETURNING id, user_id, device_id, device_type, device_name, ip, country, access_token_hash, refresh_token_hash, current_refresh_key, access_expires_at, refresh_expires_at, revoked_at, created_at, last_seen_at
`

type UpsertSessionParams struct {
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID         string             `db:"device_id" json:"device_id"`
	DeviceType       string             `db:"device_type" json:"device_type"`
	DeviceName       pgtype.Text        `db:"device_name" json:"device_name"`
	Ip               *netip.Addr        `db:"ip" json:"ip"`
	Country          pgtype.Text        `db:"country" json:"country"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at" json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at" json:"refresh_expires_at"`
}

// access_token_hash / refresh_token_hash are nullable since the source of
// truth for token validity moved to the auth_tokens table. We no longer
// write them.
func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (*models.AuthSession, error) {
	row := q.db.QueryRow(ctx, upsertSession,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceType,
		arg.DeviceName,
		arg.Ip,
		arg.Country,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i models.AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.Ip,
		&i.Country,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.CurrentRefreshKey,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return &i, err
}
