// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_vault.sql

package repo_user_vault

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

const createUserVault = `-- name: CreateUserVault :exec
INSERT INTO user_vault (
    user_id, verifier, wrapped_vault_key,
    recovery_salt, recovery_wrapped_vault_key, recovery_proof_hash
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserVaultParams struct {
	UserID                  uuid.UUID `db:"user_id" json:"user_id"`
	Verifier                []byte    `db:"verifier" json:"verifier"`
	WrappedVaultKey         []byte    `db:"wrapped_vault_key" json:"wrapped_vault_key"`
	RecoverySalt            []byte    `db:"recovery_salt" json:"recovery_salt"`
	RecoveryWrappedVaultKey []byte    `db:"recovery_wrapped_vault_key" json:"recovery_wrapped_vault_key"`
	RecoveryProofHash       string    `db:"recovery_proof_hash" json:"recovery_proof_hash"`
}

func (q *Queries) CreateUserVault(ctx context.Context, arg CreateUserVaultParams) error {
	_, err := q.db.Exec(ctx, createUserVault,
		arg.UserID,
		arg.Verifier,
		arg.WrappedVaultKey,
		arg.RecoverySalt,
		arg.RecoveryWrappedVaultKey,
		arg.RecoveryProofHash,
	)
	return err
}

const getUserVault = `-- name: GetUserVault :one
SELECT user_id, verifier, wrapped_vault_key, vault_key_version, recovery_salt, recovery_wrapped_vault_key, recovery_proof_hash, recovery_used_at FROM user_vault WHERE user_id = $1
`

func (q *Queries) GetUserVault(ctx context.Context, userID uuid.UUID) (*models.UserVault, error) {
	row := q.db.QueryRow(ctx, getUserVault, userID)
	var i models.UserVault
	err := row.Scan(
		&i.UserID,
		&i.Verifier,
		&i.WrappedVaultKey,
		&i.VaultKeyVersion,
		&i.RecoverySalt,
		&i.RecoveryWrappedVaultKey,
		&i.RecoveryProofHash,
		&i.RecoveryUsedAt,
	)
	return &i, err
}

const updateUserVaultPassword = `-- name: UpdateUserVaultPassword :exec
UPDATE user_vault
SET verifier          = $2,
    wrapped_vault_key = $3,
    vault_key_version = vault_key_version + 1
WHERE user_id = $1
`

type UpdateUserVaultPasswordParams struct {
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	Verifier        []byte    `db:"verifier" json:"verifier"`
	WrappedVaultKey []byte    `db:"wrapped_vault_key" json:"wrapped_vault_key"`
}

func (q *Queries) UpdateUserVaultPassword(ctx context.Context, arg UpdateUserVaultPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserVaultPassword, arg.UserID, arg.Verifier, arg.WrappedVaultKey)
	return err
}
