// Code generated by pgxgen. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"net/netip"
)

type AuditAction string

const (
	AuditActionRegister         AuditAction = "register"
	AuditActionLogin            AuditAction = "login"
	AuditActionLogout           AuditAction = "logout"
	AuditActionRefresh          AuditAction = "refresh"
	AuditActionPasswordChange   AuditAction = "password_change"
	AuditActionRecoveryStart    AuditAction = "recovery_start"
	AuditActionRecoveryComplete AuditAction = "recovery_complete"
	AuditActionWebauthnRegister AuditAction = "webauthn_register"
	AuditActionWebauthnRemove   AuditAction = "webauthn_remove"
	AuditActionTotpEnable       AuditAction = "totp_enable"
	AuditActionTotpDisable      AuditAction = "totp_disable"
	AuditActionProjectCreate    AuditAction = "project_create"
	AuditActionProjectUpdate    AuditAction = "project_update"
	AuditActionProjectDelete    AuditAction = "project_delete"
	AuditActionEntryCreate      AuditAction = "entry_create"
	AuditActionEntryUpdate      AuditAction = "entry_update"
	AuditActionEntryView        AuditAction = "entry_view"
	AuditActionEntryDelete      AuditAction = "entry_delete"
	AuditActionSessionTerminate AuditAction = "session_terminate"
	AuditActionAccountDelete    AuditAction = "account_delete"
	AuditActionEmailVerify      AuditAction = "email_verify"
	AuditActionEmailResend      AuditAction = "email_resend"
)

func (e AuditAction) Valid() bool {
	switch e {
	case AuditActionRegister,
		AuditActionLogin,
		AuditActionLogout,
		AuditActionRefresh,
		AuditActionPasswordChange,
		AuditActionRecoveryStart,
		AuditActionRecoveryComplete,
		AuditActionWebauthnRegister,
		AuditActionWebauthnRemove,
		AuditActionTotpEnable,
		AuditActionTotpDisable,
		AuditActionProjectCreate,
		AuditActionProjectUpdate,
		AuditActionProjectDelete,
		AuditActionEntryCreate,
		AuditActionEntryUpdate,
		AuditActionEntryView,
		AuditActionEntryDelete,
		AuditActionSessionTerminate,
		AuditActionAccountDelete,
		AuditActionEmailVerify,
		AuditActionEmailResend:
		return true
	}
	return false
}

type EntryKind string

const (
	EntryKindLogin    EntryKind = "login"
	EntryKindTotp     EntryKind = "totp"
	EntryKindCard     EntryKind = "card"
	EntryKindIdentity EntryKind = "identity"
	EntryKindSshKey   EntryKind = "ssh_key"
	EntryKindNote     EntryKind = "note"
)

func (e EntryKind) Valid() bool {
	switch e {
	case EntryKindLogin,
		EntryKindTotp,
		EntryKindCard,
		EntryKindIdentity,
		EntryKindSshKey,
		EntryKindNote:
		return true
	}
	return false
}

type AuditLog struct {
	ID        int64              `db:"id" json:"id"`
	UserID    uuid.NullUUID      `db:"user_id" json:"user_id"`
	Action    AuditAction        `db:"action" json:"action"`
	TargetID  uuid.NullUUID      `db:"target_id" json:"target_id"`
	Ip        *netip.Addr        `db:"ip" json:"ip"`
	UserAgent pgtype.Text        `db:"user_agent" json:"user_agent"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	PrevHash  []byte             `db:"prev_hash" json:"prev_hash"`
	SelfHash  []byte             `db:"self_hash" json:"self_hash"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthSession struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	UserID            uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID          string             `db:"device_id" json:"device_id"`
	DeviceType        string             `db:"device_type" json:"device_type"`
	DeviceName        pgtype.Text        `db:"device_name" json:"device_name"`
	Ip                *netip.Addr        `db:"ip" json:"ip"`
	Country           pgtype.Text        `db:"country" json:"country"`
	AccessTokenHash   []byte             `db:"access_token_hash" json:"access_token_hash"`
	RefreshTokenHash  []byte             `db:"refresh_token_hash" json:"refresh_token_hash"`
	CurrentRefreshKey []byte             `db:"current_refresh_key" json:"current_refresh_key"`
	AccessExpiresAt   pgtype.Timestamptz `db:"access_expires_at" json:"access_expires_at"`
	RefreshExpiresAt  pgtype.Timestamptz `db:"refresh_expires_at" json:"refresh_expires_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt        pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

type AuthToken struct {
	Key       []byte             `db:"key" json:"key"`
	Value     []byte             `db:"value" json:"value"`
	UserID    uuid.NullUUID      `db:"user_id" json:"user_id"`
	SessionID uuid.NullUUID      `db:"session_id" json:"session_id"`
	TokenType string             `db:"token_type" json:"token_type"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EmailVerificationToken struct {
	TokenHash  []byte             `db:"token_hash" json:"token_hash"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Purpose    string             `db:"purpose" json:"purpose"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type Entry struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	ProjectID      uuid.NullUUID      `db:"project_id" json:"project_id"`
	Kind           EntryKind          `db:"kind" json:"kind"`
	EncryptedBlob  []byte             `db:"encrypted_blob" json:"encrypted_blob"`
	WrappedItemKey []byte             `db:"wrapped_item_key" json:"wrapped_item_key"`
	TitleHash      []byte             `db:"title_hash" json:"title_hash"`
	DomainHash     []byte             `db:"domain_hash" json:"domain_hash"`
	HasTotp        bool               `db:"has_totp" json:"has_totp"`
	IsFavorite     bool               `db:"is_favorite" json:"is_favorite"`
	Version        int32              `db:"version" json:"version"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IdempotencyKey struct {
	Key            string             `db:"key" json:"key"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Procedure      string             `db:"procedure" json:"procedure"`
	RequestHash    []byte             `db:"request_hash" json:"request_hash"`
	ResponseStatus int32              `db:"response_status" json:"response_status"`
	ResponseBody   []byte             `db:"response_body" json:"response_body"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type Project struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	EncryptedBlob  []byte             `db:"encrypted_blob" json:"encrypted_blob"`
	WrappedItemKey []byte             `db:"wrapped_item_key" json:"wrapped_item_key"`
	NameHash       []byte             `db:"name_hash" json:"name_hash"`
	Version        int32              `db:"version" json:"version"`
	SortOrder      int32              `db:"sort_order" json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SystemState struct {
	Key       string             `db:"key" json:"key"`
	Value     []byte             `db:"value" json:"value"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserAuth struct {
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	AuthKeyHash    string             `db:"auth_key_hash" json:"auth_key_hash"`
	FailedAttempts int32              `db:"failed_attempts" json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
}

type UserKdfParam struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	SaltUser   []byte    `db:"salt_user" json:"salt_user"`
	Argon2T    int32     `db:"argon2_t" json:"argon2_t"`
	Argon2MKib int32     `db:"argon2_m_kib" json:"argon2_m_kib"`
	Argon2P    int32     `db:"argon2_p" json:"argon2_p"`
	Algo       string    `db:"algo" json:"algo"`
}

type UserLoginTotp struct {
	UserID          uuid.UUID          `db:"user_id" json:"user_id"`
	EncryptedSecret []byte             `db:"encrypted_secret" json:"encrypted_secret"`
	Nonce           []byte             `db:"nonce" json:"nonce"`
	Enabled         bool               `db:"enabled" json:"enabled"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserVault struct {
	UserID                  uuid.UUID          `db:"user_id" json:"user_id"`
	Verifier                []byte             `db:"verifier" json:"verifier"`
	WrappedVaultKey         []byte             `db:"wrapped_vault_key" json:"wrapped_vault_key"`
	VaultKeyVersion         int32              `db:"vault_key_version" json:"vault_key_version"`
	RecoverySalt            []byte             `db:"recovery_salt" json:"recovery_salt"`
	RecoveryWrappedVaultKey []byte             `db:"recovery_wrapped_vault_key" json:"recovery_wrapped_vault_key"`
	RecoveryProofHash       string             `db:"recovery_proof_hash" json:"recovery_proof_hash"`
	RecoveryUsedAt          pgtype.Timestamptz `db:"recovery_used_at" json:"recovery_used_at"`
}

type UserWebauthnCredential struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	Name         string             `db:"name" json:"name"`
	CredentialID []byte             `db:"credential_id" json:"credential_id"`
	PublicKey    []byte             `db:"public_key" json:"public_key"`
	Aaguid       []byte             `db:"aaguid" json:"aaguid"`
	SignCount    int64              `db:"sign_count" json:"sign_count"`
	Transports   []string           `db:"transports" json:"transports"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt   pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}
