// Code generated by pgxgen. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"net/netip"
)

type AuthSession struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID         string             `db:"device_id" json:"device_id"`
	DeviceType       string             `db:"device_type" json:"device_type"`
	DeviceName       pgtype.Text        `db:"device_name" json:"device_name"`
	Ip               *netip.Addr        `db:"ip" json:"ip"`
	Country          pgtype.Text        `db:"country" json:"country"`
	AccessTokenHash  []byte             `db:"access_token_hash" json:"access_token_hash"`
	RefreshTokenHash []byte             `db:"refresh_token_hash" json:"refresh_token_hash"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at" json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at" json:"refresh_expires_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

type User struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserAuth struct {
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	AuthKeyHash    string             `db:"auth_key_hash" json:"auth_key_hash"`
	FailedAttempts int32              `db:"failed_attempts" json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
}

type UserKdfParam struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	SaltUser   []byte    `db:"salt_user" json:"salt_user"`
	Argon2T    int32     `db:"argon2_t" json:"argon2_t"`
	Argon2MKib int32     `db:"argon2_m_kib" json:"argon2_m_kib"`
	Argon2P    int32     `db:"argon2_p" json:"argon2_p"`
	Algo       string    `db:"algo" json:"algo"`
}

type UserLoginTotp struct {
	UserID          uuid.UUID          `db:"user_id" json:"user_id"`
	EncryptedSecret []byte             `db:"encrypted_secret" json:"encrypted_secret"`
	Nonce           []byte             `db:"nonce" json:"nonce"`
	Enabled         bool               `db:"enabled" json:"enabled"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserVault struct {
	UserID                  uuid.UUID          `db:"user_id" json:"user_id"`
	Verifier                []byte             `db:"verifier" json:"verifier"`
	WrappedVaultKey         []byte             `db:"wrapped_vault_key" json:"wrapped_vault_key"`
	VaultKeyVersion         int32              `db:"vault_key_version" json:"vault_key_version"`
	RecoverySalt            []byte             `db:"recovery_salt" json:"recovery_salt"`
	RecoveryWrappedVaultKey []byte             `db:"recovery_wrapped_vault_key" json:"recovery_wrapped_vault_key"`
	RecoveryProofHash       string             `db:"recovery_proof_hash" json:"recovery_proof_hash"`
	RecoveryUsedAt          pgtype.Timestamptz `db:"recovery_used_at" json:"recovery_used_at"`
}
