// Code generated by pgxgen. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type DelegationResourceType string

const (
	DelegationResourceTypeEnergy    DelegationResourceType = "energy"
	DelegationResourceTypeBandwidth DelegationResourceType = "bandwidth"
)

func (e DelegationResourceType) Valid() bool {
	switch e {
	case DelegationResourceTypeEnergy,
		DelegationResourceTypeBandwidth:
		return true
	}
	return false
}

type DelegationStatus string

const (
	DelegationStatusPending    DelegationStatus = "pending"
	DelegationStatusProcessing DelegationStatus = "processing"
	DelegationStatusCompleted  DelegationStatus = "completed"
	DelegationStatusFailed     DelegationStatus = "failed"
)

func (e DelegationStatus) Valid() bool {
	switch e {
	case DelegationStatusPending,
		DelegationStatusProcessing,
		DelegationStatusCompleted,
		DelegationStatusFailed:
		return true
	}
	return false
}

type DelegationOrder struct {
	ID              uuid.UUID              `db:"id" json:"id"`
	WalletID        uuid.NullUUID          `db:"wallet_id" json:"wallet_id"`
	TargetAddress   string                 `db:"target_address" json:"target_address"`
	ResourceType    DelegationResourceType `db:"resource_type" json:"resource_type"`
	Amount          int64                  `db:"amount" json:"amount"`
	Period          string                 `db:"period" json:"period"`
	Status          DelegationStatus       `db:"status" json:"status"`
	Provider        string                 `db:"provider" json:"provider"`
	ProviderOrderID pgtype.Text            `db:"provider_order_id" json:"provider_order_id"`
	ErrorMessage    pgtype.Text            `db:"error_message" json:"error_message"`
	IsManual        bool                   `db:"is_manual" json:"is_manual"`
	CreatedAt       pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
	CostTrx         decimal.NullDecimal    `db:"cost_trx" json:"cost_trx"`
	TxHash          pgtype.Text            `db:"tx_hash" json:"tx_hash"`
	DeliveredAmount pgtype.Int8            `db:"delivered_amount" json:"delivered_amount"`
}

type Setting struct {
	Key       string             `db:"key" json:"key"`
	Value     []byte             `db:"value" json:"value"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Wallet struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	Name                    string             `db:"name" json:"name"`
	Address                 string             `db:"address" json:"address"`
	Blockchain              string             `db:"blockchain" json:"blockchain"`
	EnergyThreshold         int64              `db:"energy_threshold" json:"energy_threshold"`
	BandwidthThreshold      int64              `db:"bandwidth_threshold" json:"bandwidth_threshold"`
	EnergyDelegateAmount    int64              `db:"energy_delegate_amount" json:"energy_delegate_amount"`
	BandwidthDelegateAmount int64              `db:"bandwidth_delegate_amount" json:"bandwidth_delegate_amount"`
	EnergyPeriod            string             `db:"energy_period" json:"energy_period"`
	BandwidthPeriod         string             `db:"bandwidth_period" json:"bandwidth_period"`
	IsActive                bool               `db:"is_active" json:"is_active"`
	CurrentEnergy           int64              `db:"current_energy" json:"current_energy"`
	CurrentBandwidth        int64              `db:"current_bandwidth" json:"current_bandwidth"`
	CurrentBalance          string             `db:"current_balance" json:"current_balance"`
	LastCheckedAt           pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
