// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package repo_auth_tokens

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const authTokenExists = `-- name: AuthTokenExists :one
SELECT EXISTS(
    SELECT 1 FROM auth_tokens WHERE key = $1 AND expires_at > now()
)
`

func (q *Queries) AuthTokenExists(ctx context.Context, key []byte) (bool, error) {
	row := q.db.QueryRow(ctx, authTokenExists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAuthToken = `-- name: DeleteAuthToken :exec
DELETE FROM auth_tokens WHERE key = $1
`

func (q *Queries) DeleteAuthToken(ctx context.Context, key []byte) error {
	_, err := q.db.Exec(ctx, deleteAuthToken, key)
	return err
}

const deleteAuthTokensBySession = `-- name: DeleteAuthTokensBySession :execrows
DELETE FROM auth_tokens WHERE session_id = $1
`

func (q *Queries) DeleteAuthTokensBySession(ctx context.Context, sessionID uuid.NullUUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthTokensBySession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAuthTokensByUser = `-- name: DeleteAuthTokensByUser :execrows
DELETE FROM auth_tokens
WHERE user_id = $1
  AND ($2::uuid IS NULL OR session_id <> $2)
`

type DeleteAuthTokensByUserParams struct {
	UserID          uuid.NullUUID `db:"user_id" json:"user_id"`
	ExceptSessionID uuid.NullUUID `db:"except_session_id" json:"except_session_id"`
}

func (q *Queries) DeleteAuthTokensByUser(ctx context.Context, arg DeleteAuthTokensByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthTokensByUser, arg.UserID, arg.ExceptSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :execrows
DELETE FROM auth_tokens WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthToken = `-- name: GetAuthToken :one
SELECT key, value, user_id, session_id, token_type, expires_at, created_at
FROM auth_tokens
WHERE key = $1 AND expires_at > now()
`

func (q *Queries) GetAuthToken(ctx context.Context, key []byte) (*models.AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthToken, key)
	var i models.AuthToken
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UserID,
		&i.SessionID,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listAuthTokensByPrefix = `-- name: ListAuthTokensByPrefix :many
SELECT key, value FROM auth_tokens
WHERE expires_at > now()
  AND ($1::bytea = ''::bytea OR key >= $1::bytea AND key < ($1::bytea || E'\\xFF'::bytea))
`

type ListAuthTokensByPrefixRow struct {
	Key   []byte `db:"key" json:"key"`
	Value []byte `db:"value" json:"value"`
}

// Used by tokenmanager.ITokenStore.Keys / KeysAndValues. Empty prefix → all rows.
func (q *Queries) ListAuthTokensByPrefix(ctx context.Context, prefix []byte) ([]*ListAuthTokensByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listAuthTokensByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAuthTokensByPrefixRow{}
	for rows.Next() {
		var i ListAuthTokensByPrefixRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuthToken = `-- name: UpsertAuthToken :exec
INSERT INTO auth_tokens (key, value, user_id, session_id, token_type, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (key) DO UPDATE
SET value      = EXCLUDED.value,
    user_id    = EXCLUDED.user_id,
    session_id = EXCLUDED.session_id,
    token_type = EXCLUDED.token_type,
    expires_at = EXCLUDED.expires_at
`

type UpsertAuthTokenParams struct {
	Key       []byte             `db:"key" json:"key"`
	Value     []byte             `db:"value" json:"value"`
	UserID    uuid.NullUUID      `db:"user_id" json:"user_id"`
	SessionID uuid.NullUUID      `db:"session_id" json:"session_id"`
	TokenType string             `db:"token_type" json:"token_type"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) UpsertAuthToken(ctx context.Context, arg UpsertAuthTokenParams) error {
	_, err := q.db.Exec(ctx, upsertAuthToken,
		arg.Key,
		arg.Value,
		arg.UserID,
		arg.SessionID,
		arg.TokenType,
		arg.ExpiresAt,
	)
	return err
}
