// Code generated by pgxgen. DO NOT EDIT.
package wallets

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameWallets TableName = "wallets"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameWalletsId                      ColumnName = "id"
	ColumnNameWalletsName                    ColumnName = "name"
	ColumnNameWalletsAddress                 ColumnName = "address"
	ColumnNameWalletsBlockchain              ColumnName = "blockchain"
	ColumnNameWalletsEnergyThreshold         ColumnName = "energy_threshold"
	ColumnNameWalletsBandwidthThreshold      ColumnName = "bandwidth_threshold"
	ColumnNameWalletsEnergyDelegateAmount    ColumnName = "energy_delegate_amount"
	ColumnNameWalletsBandwidthDelegateAmount ColumnName = "bandwidth_delegate_amount"
	ColumnNameWalletsEnergyPeriod            ColumnName = "energy_period"
	ColumnNameWalletsBandwidthPeriod         ColumnName = "bandwidth_period"
	ColumnNameWalletsIsActive                ColumnName = "is_active"
	ColumnNameWalletsCurrentEnergy           ColumnName = "current_energy"
	ColumnNameWalletsCurrentBandwidth        ColumnName = "current_bandwidth"
	ColumnNameWalletsCurrentBalance          ColumnName = "current_balance"
	ColumnNameWalletsLastCheckedAt           ColumnName = "last_checked_at"
	ColumnNameWalletsCreatedAt               ColumnName = "created_at"
	ColumnNameWalletsUpdatedAt               ColumnName = "updated_at"
)

func WalletsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameWalletsId,
		ColumnNameWalletsName,
		ColumnNameWalletsAddress,
		ColumnNameWalletsBlockchain,
		ColumnNameWalletsEnergyThreshold,
		ColumnNameWalletsBandwidthThreshold,
		ColumnNameWalletsEnergyDelegateAmount,
		ColumnNameWalletsBandwidthDelegateAmount,
		ColumnNameWalletsEnergyPeriod,
		ColumnNameWalletsBandwidthPeriod,
		ColumnNameWalletsIsActive,
		ColumnNameWalletsCurrentEnergy,
		ColumnNameWalletsCurrentBandwidth,
		ColumnNameWalletsCurrentBalance,
		ColumnNameWalletsLastCheckedAt,
		ColumnNameWalletsCreatedAt,
		ColumnNameWalletsUpdatedAt,
	}
}
