// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package wallets

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Wallet, error)
	Delete(ctx context.Context, id uuid.UUID) error
	Find(ctx context.Context, arg FindParams) ([]*models.Wallet, error)
	FindActiveWallets(ctx context.Context) ([]*models.Wallet, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Wallet, error)
	Total(ctx context.Context) (int64, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Wallet, error)
	UpdateResources(ctx context.Context, arg UpdateResourcesParams) (*models.Wallet, error)
}

var _ Querier = (*Queries)(nil)
