// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets_extra.sql

package wallets

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

const findActiveWallets = `-- name: FindActiveWallets :many
SELECT id, name, address, blockchain, energy_threshold, bandwidth_threshold, energy_delegate_amount, bandwidth_delegate_amount, energy_period, bandwidth_period, is_active, current_energy, current_bandwidth, current_balance, last_checked_at, created_at, updated_at FROM wallets WHERE is_active = TRUE ORDER BY created_at DESC
`

func (q *Queries) FindActiveWallets(ctx context.Context) ([]*models.Wallet, error) {
	rows, err := q.db.Query(ctx, findActiveWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Wallet{}
	for rows.Next() {
		var i models.Wallet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Blockchain,
			&i.EnergyThreshold,
			&i.BandwidthThreshold,
			&i.EnergyDelegateAmount,
			&i.BandwidthDelegateAmount,
			&i.EnergyPeriod,
			&i.BandwidthPeriod,
			&i.IsActive,
			&i.CurrentEnergy,
			&i.CurrentBandwidth,
			&i.CurrentBalance,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResources = `-- name: UpdateResources :one
UPDATE wallets
  SET current_energy=$1,
      current_bandwidth=$2,
      current_balance=$3,
      last_checked_at=now(),
      updated_at=now()
WHERE id=$4
  RETURNING id, name, address, blockchain, energy_threshold, bandwidth_threshold, energy_delegate_amount, bandwidth_delegate_amount, energy_period, bandwidth_period, is_active, current_energy, current_bandwidth, current_balance, last_checked_at, created_at, updated_at
`

type UpdateResourcesParams struct {
	CurrentEnergy    int64     `db:"current_energy" json:"current_energy"`
	CurrentBandwidth int64     `db:"current_bandwidth" json:"current_bandwidth"`
	CurrentBalance   string    `db:"current_balance" json:"current_balance"`
	ID               uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateResources(ctx context.Context, arg UpdateResourcesParams) (*models.Wallet, error) {
	row := q.db.QueryRow(ctx, updateResources,
		arg.CurrentEnergy,
		arg.CurrentBandwidth,
		arg.CurrentBalance,
		arg.ID,
	)
	var i models.Wallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Blockchain,
		&i.EnergyThreshold,
		&i.BandwidthThreshold,
		&i.EnergyDelegateAmount,
		&i.BandwidthDelegateAmount,
		&i.EnergyPeriod,
		&i.BandwidthPeriod,
		&i.IsActive,
		&i.CurrentEnergy,
		&i.CurrentBandwidth,
		&i.CurrentBalance,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
