// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets_gen.sql

package wallets

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const create = `-- name: Create :one
INSERT INTO wallets (name, address, blockchain, energy_threshold, bandwidth_threshold, energy_delegate_amount, bandwidth_delegate_amount, energy_period, bandwidth_period, is_active, current_energy, current_bandwidth, current_balance, last_checked_at, created_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, now())
	RETURNING id, name, address, blockchain, energy_threshold, bandwidth_threshold, energy_delegate_amount, bandwidth_delegate_amount, energy_period, bandwidth_period, is_active, current_energy, current_bandwidth, current_balance, last_checked_at, created_at, updated_at
`

type CreateParams struct {
	Name                    string             `db:"name" json:"name"`
	Address                 string             `db:"address" json:"address"`
	Blockchain              string             `db:"blockchain" json:"blockchain"`
	EnergyThreshold         int64              `db:"energy_threshold" json:"energy_threshold"`
	BandwidthThreshold      int64              `db:"bandwidth_threshold" json:"bandwidth_threshold"`
	EnergyDelegateAmount    int64              `db:"energy_delegate_amount" json:"energy_delegate_amount"`
	BandwidthDelegateAmount int64              `db:"bandwidth_delegate_amount" json:"bandwidth_delegate_amount"`
	EnergyPeriod            string             `db:"energy_period" json:"energy_period"`
	BandwidthPeriod         string             `db:"bandwidth_period" json:"bandwidth_period"`
	IsActive                bool               `db:"is_active" json:"is_active"`
	CurrentEnergy           int64              `db:"current_energy" json:"current_energy"`
	CurrentBandwidth        int64              `db:"current_bandwidth" json:"current_bandwidth"`
	CurrentBalance          string             `db:"current_balance" json:"current_balance"`
	LastCheckedAt           pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Wallet, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.Address,
		arg.Blockchain,
		arg.EnergyThreshold,
		arg.BandwidthThreshold,
		arg.EnergyDelegateAmount,
		arg.BandwidthDelegateAmount,
		arg.EnergyPeriod,
		arg.BandwidthPeriod,
		arg.IsActive,
		arg.CurrentEnergy,
		arg.CurrentBandwidth,
		arg.CurrentBalance,
		arg.LastCheckedAt,
	)
	var i models.Wallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Blockchain,
		&i.EnergyThreshold,
		&i.BandwidthThreshold,
		&i.EnergyDelegateAmount,
		&i.BandwidthDelegateAmount,
		&i.EnergyPeriod,
		&i.BandwidthPeriod,
		&i.IsActive,
		&i.CurrentEnergy,
		&i.CurrentBandwidth,
		&i.CurrentBalance,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM wallets WHERE id=$1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const find = `-- name: Find :many
SELECT id, name, address, blockchain, energy_threshold, bandwidth_threshold, energy_delegate_amount, bandwidth_delegate_amount, energy_period, bandwidth_period, is_active, current_energy, current_bandwidth, current_balance, last_checked_at, created_at, updated_at FROM wallets ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type FindParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) Find(ctx context.Context, arg FindParams) ([]*models.Wallet, error) {
	rows, err := q.db.Query(ctx, find, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Wallet{}
	for rows.Next() {
		var i models.Wallet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Blockchain,
			&i.EnergyThreshold,
			&i.BandwidthThreshold,
			&i.EnergyDelegateAmount,
			&i.BandwidthDelegateAmount,
			&i.EnergyPeriod,
			&i.BandwidthPeriod,
			&i.IsActive,
			&i.CurrentEnergy,
			&i.CurrentBandwidth,
			&i.CurrentBalance,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, name, address, blockchain, energy_threshold, bandwidth_threshold, energy_delegate_amount, bandwidth_delegate_amount, energy_period, bandwidth_period, is_active, current_energy, current_bandwidth, current_balance, last_checked_at, created_at, updated_at FROM wallets WHERE id=$1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (*models.Wallet, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i models.Wallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Blockchain,
		&i.EnergyThreshold,
		&i.BandwidthThreshold,
		&i.EnergyDelegateAmount,
		&i.BandwidthDelegateAmount,
		&i.EnergyPeriod,
		&i.BandwidthPeriod,
		&i.IsActive,
		&i.CurrentEnergy,
		&i.CurrentBandwidth,
		&i.CurrentBalance,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const total = `-- name: Total :one
SELECT count(1) as total FROM wallets
`

func (q *Queries) Total(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, total)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const update = `-- name: Update :one
UPDATE wallets
	SET name=$1, address=$2, blockchain=$3, energy_threshold=$4, bandwidth_threshold=$5, energy_delegate_amount=$6, bandwidth_delegate_amount=$7, energy_period=$8, bandwidth_period=$9, is_active=$10, current_energy=$11, current_bandwidth=$12, current_balance=$13, last_checked_at=$14, updated_at=now()
WHERE id=$15
	RETURNING id, name, address, blockchain, energy_threshold, bandwidth_threshold, energy_delegate_amount, bandwidth_delegate_amount, energy_period, bandwidth_period, is_active, current_energy, current_bandwidth, current_balance, last_checked_at, created_at, updated_at
`

type UpdateParams struct {
	Name                    string             `db:"name" json:"name"`
	Address                 string             `db:"address" json:"address"`
	Blockchain              string             `db:"blockchain" json:"blockchain"`
	EnergyThreshold         int64              `db:"energy_threshold" json:"energy_threshold"`
	BandwidthThreshold      int64              `db:"bandwidth_threshold" json:"bandwidth_threshold"`
	EnergyDelegateAmount    int64              `db:"energy_delegate_amount" json:"energy_delegate_amount"`
	BandwidthDelegateAmount int64              `db:"bandwidth_delegate_amount" json:"bandwidth_delegate_amount"`
	EnergyPeriod            string             `db:"energy_period" json:"energy_period"`
	BandwidthPeriod         string             `db:"bandwidth_period" json:"bandwidth_period"`
	IsActive                bool               `db:"is_active" json:"is_active"`
	CurrentEnergy           int64              `db:"current_energy" json:"current_energy"`
	CurrentBandwidth        int64              `db:"current_bandwidth" json:"current_bandwidth"`
	CurrentBalance          string             `db:"current_balance" json:"current_balance"`
	LastCheckedAt           pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	ID                      uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.Wallet, error) {
	row := q.db.QueryRow(ctx, update,
		arg.Name,
		arg.Address,
		arg.Blockchain,
		arg.EnergyThreshold,
		arg.BandwidthThreshold,
		arg.EnergyDelegateAmount,
		arg.BandwidthDelegateAmount,
		arg.EnergyPeriod,
		arg.BandwidthPeriod,
		arg.IsActive,
		arg.CurrentEnergy,
		arg.CurrentBandwidth,
		arg.CurrentBalance,
		arg.LastCheckedAt,
		arg.ID,
	)
	var i models.Wallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Blockchain,
		&i.EnergyThreshold,
		&i.BandwidthThreshold,
		&i.EnergyDelegateAmount,
		&i.BandwidthDelegateAmount,
		&i.EnergyPeriod,
		&i.BandwidthPeriod,
		&i.IsActive,
		&i.CurrentEnergy,
		&i.CurrentBandwidth,
		&i.CurrentBalance,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
