// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_auth.sql

package repo_user_auth

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const getUserAuth = `-- name: GetUserAuth :one
SELECT user_id, auth_key_hash, failed_attempts, locked_until, recovery_failed_attempts, recovery_locked_until FROM user_auth WHERE user_id = $1
`

func (q *Queries) GetUserAuth(ctx context.Context, userID uuid.UUID) (*models.UserAuth, error) {
	row := q.db.QueryRow(ctx, getUserAuth, userID)
	var i models.UserAuth
	err := row.Scan(
		&i.UserID,
		&i.AuthKeyHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.RecoveryFailedAttempts,
		&i.RecoveryLockedUntil,
	)
	return &i, err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE user_auth
SET failed_attempts = failed_attempts + 1,
    locked_until    = CASE
        WHEN failed_attempts + 1 >= 5 AND (locked_until IS NULL OR locked_until <= now())
            THEN now() + interval '15 minutes'
        ELSE locked_until
    END
WHERE user_id = $1
RETURNING failed_attempts, locked_until
`

type RecordFailedLoginRow struct {
	FailedAttempts int32              `db:"failed_attempts" json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
}

// Bumps failed_attempts and (re-)arms locked_until whenever the count is at
// or above the threshold AND no lock is currently active. Re-arming on every
// post-threshold attempt (not only the exact 5th) means the account keeps
// re-locking after each window expires, so brute-force stays bounded (H-1
// fix). The "no active lock" guard means a trickle of bad attempts cannot
// *extend* a lock that is already running — Authorize refuses before calling
// this while locked, so in practice the counter sits at the threshold for the
// whole window and re-locks on the first attempt after it lapses.
func (q *Queries) RecordFailedLogin(ctx context.Context, userID uuid.UUID) (*RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, userID)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return &i, err
}

const recordFailedRecovery = `-- name: RecordFailedRecovery :one
UPDATE user_auth
SET recovery_failed_attempts = recovery_failed_attempts + 1,
    recovery_locked_until    = CASE
        WHEN recovery_failed_attempts + 1 >= 5 AND (recovery_locked_until IS NULL OR recovery_locked_until <= now())
            THEN now() + interval '1 hour'
        ELSE recovery_locked_until
    END
WHERE user_id = $1
RETURNING recovery_failed_attempts, recovery_locked_until
`

type RecordFailedRecoveryRow struct {
	RecoveryFailedAttempts int32              `db:"recovery_failed_attempts" json:"recovery_failed_attempts"`
	RecoveryLockedUntil    pgtype.Timestamptz `db:"recovery_locked_until" json:"recovery_locked_until"`
}

// Recovery-specific failure counter so a brute-force of the recovery proof
// is bounded independently of the password-lockout counter (M-9). Same
// re-arming semantics as RecordFailedLogin: (re-)lock whenever the count is
// at or above the threshold and no lock is currently active, so the account
// keeps re-locking after each window lapses rather than only once. A longer
// window (1 hour) is fine because recovery is a rarely-used flow.
func (q *Queries) RecordFailedRecovery(ctx context.Context, userID uuid.UUID) (*RecordFailedRecoveryRow, error) {
	row := q.db.QueryRow(ctx, recordFailedRecovery, userID)
	var i RecordFailedRecoveryRow
	err := row.Scan(&i.RecoveryFailedAttempts, &i.RecoveryLockedUntil)
	return &i, err
}

const resetFailedLogin = `-- name: ResetFailedLogin :exec
UPDATE user_auth
SET failed_attempts = 0,
    locked_until    = NULL
WHERE user_id = $1
`

func (q *Queries) ResetFailedLogin(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLogin, userID)
	return err
}

const resetFailedRecovery = `-- name: ResetFailedRecovery :exec
UPDATE user_auth
SET recovery_failed_attempts = 0,
    recovery_locked_until    = NULL
WHERE user_id = $1
`

func (q *Queries) ResetFailedRecovery(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedRecovery, userID)
	return err
}

const upsertUserAuth = `-- name: UpsertUserAuth :exec
INSERT INTO user_auth (user_id, auth_key_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET auth_key_hash   = EXCLUDED.auth_key_hash,
    failed_attempts = 0,
    locked_until    = NULL
`

type UpsertUserAuthParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	AuthKeyHash string    `db:"auth_key_hash" json:"auth_key_hash"`
}

func (q *Queries) UpsertUserAuth(ctx context.Context, arg UpsertUserAuthParams) error {
	_, err := q.db.Exec(ctx, upsertUserAuth, arg.UserID, arg.AuthKeyHash)
	return err
}
