// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_state.sql

package repo_system_state

import (
	"context"
)

const getSystemValue = `-- name: GetSystemValue :one
SELECT value FROM system_state WHERE key = $1
`

func (q *Queries) GetSystemValue(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSystemValue, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const upsertSystemValue = `-- name: UpsertSystemValue :exec
INSERT INTO system_state (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
`

type UpsertSystemValueParams struct {
	Key   string `db:"key" json:"key"`
	Value []byte `db:"value" json:"value"`
}

func (q *Queries) UpsertSystemValue(ctx context.Context, arg UpsertSystemValueParams) error {
	_, err := q.db.Exec(ctx, upsertSystemValue, arg.Key, arg.Value)
	return err
}
