// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_chain_anchors.sql

package repo_audit_chain_anchors

import (
	"context"

	"github.com/sxwebdev/oblivio/internal/models"
)

const getLatestAuditChainAnchor = `-- name: GetLatestAuditChainAnchor :one
SELECT id, head, signature, signed_at, signer_id FROM audit_chain_anchors
ORDER BY signed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAuditChainAnchor(ctx context.Context) (*models.AuditChainAnchor, error) {
	row := q.db.QueryRow(ctx, getLatestAuditChainAnchor)
	var i models.AuditChainAnchor
	err := row.Scan(
		&i.ID,
		&i.Head,
		&i.Signature,
		&i.SignedAt,
		&i.SignerID,
	)
	return &i, err
}

const insertAuditChainAnchor = `-- name: InsertAuditChainAnchor :one
INSERT INTO audit_chain_anchors (head, signature, signer_id)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertAuditChainAnchorParams struct {
	Head      []byte `db:"head" json:"head"`
	Signature []byte `db:"signature" json:"signature"`
	SignerID  string `db:"signer_id" json:"signer_id"`
}

func (q *Queries) InsertAuditChainAnchor(ctx context.Context, arg InsertAuditChainAnchorParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAuditChainAnchor, arg.Head, arg.Signature, arg.SignerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
