// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package repo_projects

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    user_id, encrypted_blob, wrapped_item_key, name_hash, sort_order
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, encrypted_blob, wrapped_item_key, name_hash, version, sort_order, created_at, updated_at
`

type CreateProjectParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	EncryptedBlob  []byte    `db:"encrypted_blob" json:"encrypted_blob"`
	WrappedItemKey []byte    `db:"wrapped_item_key" json:"wrapped_item_key"`
	NameHash       []byte    `db:"name_hash" json:"name_hash"`
	SortOrder      int32     `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (*models.Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.EncryptedBlob,
		arg.WrappedItemKey,
		arg.NameHash,
		arg.SortOrder,
	)
	var i models.Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedBlob,
		&i.WrappedItemKey,
		&i.NameHash,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE id = $1 AND user_id = $2 AND version = $3
`

type DeleteProjectParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	ExpectedVersion int32     `db:"expected_version" json:"expected_version"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, encrypted_blob, wrapped_item_key, name_hash, version, sort_order, created_at, updated_at FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (*models.Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i models.Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedBlob,
		&i.WrappedItemKey,
		&i.NameHash,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, encrypted_blob, wrapped_item_key, name_hash, version, sort_order, created_at, updated_at FROM projects
WHERE user_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProjects(ctx context.Context, userID uuid.UUID) ([]*models.Project, error) {
	rows, err := q.db.Query(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Project{}
	for rows.Next() {
		var i models.Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EncryptedBlob,
			&i.WrappedItemKey,
			&i.NameHash,
			&i.Version,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderProject = `-- name: ReorderProject :exec
UPDATE projects SET sort_order = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type ReorderProjectParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	SortOrder int32     `db:"sort_order" json:"sort_order"`
}

func (q *Queries) ReorderProject(ctx context.Context, arg ReorderProjectParams) error {
	_, err := q.db.Exec(ctx, reorderProject, arg.ID, arg.UserID, arg.SortOrder)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET encrypted_blob   = $3,
    wrapped_item_key = $4,
    name_hash        = $5,
    version          = version + 1,
    updated_at       = now()
WHERE id = $1 AND user_id = $2 AND version = $6
RETURNING id, user_id, encrypted_blob, wrapped_item_key, name_hash, version, sort_order, created_at, updated_at
`

type UpdateProjectParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	EncryptedBlob   []byte    `db:"encrypted_blob" json:"encrypted_blob"`
	WrappedItemKey  []byte    `db:"wrapped_item_key" json:"wrapped_item_key"`
	NameHash        []byte    `db:"name_hash" json:"name_hash"`
	ExpectedVersion int32     `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (*models.Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UserID,
		arg.EncryptedBlob,
		arg.WrappedItemKey,
		arg.NameHash,
		arg.ExpectedVersion,
	)
	var i models.Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedBlob,
		&i.WrappedItemKey,
		&i.NameHash,
		&i.Version,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
