// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa_challenges.sql

package repo_mfa_challenges

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const deleteExpiredMFAChallenges = `-- name: DeleteExpiredMFAChallenges :execrows
DELETE FROM mfa_challenges WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredMFAChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMFAChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMFAChallenge = `-- name: DeleteMFAChallenge :execrows
DELETE FROM mfa_challenges WHERE id = $1
`

func (q *Queries) DeleteMFAChallenge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMFAChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMFAChallenge = `-- name: GetMFAChallenge :one
SELECT id, user_id, email, auth_key_ct, device_id, device_type, device_name, totp_required, webauthn_state, expires_at, failed_attempts FROM mfa_challenges WHERE id = $1
`

func (q *Queries) GetMFAChallenge(ctx context.Context, id uuid.UUID) (*models.MfaChallenge, error) {
	row := q.db.QueryRow(ctx, getMFAChallenge, id)
	var i models.MfaChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.AuthKeyCt,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.TotpRequired,
		&i.WebauthnState,
		&i.ExpiresAt,
		&i.FailedAttempts,
	)
	return &i, err
}

const incrementMFAFailedAttempts = `-- name: IncrementMFAFailedAttempts :one
UPDATE mfa_challenges
SET failed_attempts = failed_attempts + 1
WHERE id = $1
RETURNING failed_attempts
`

// Bumps failed_attempts. Returns the new count. The Go caller decides
// whether to burn the row (DeleteMFAChallenge) when the threshold is hit.
func (q *Queries) IncrementMFAFailedAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementMFAFailedAttempts, id)
	var failed_attempts int32
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const insertMFAChallenge = `-- name: InsertMFAChallenge :one
INSERT INTO mfa_challenges (
    id, user_id, email, auth_key_ct,
    device_id, device_type, device_name,
    totp_required, webauthn_state, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertMFAChallengeParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	Email         string             `db:"email" json:"email"`
	AuthKeyCt     []byte             `db:"auth_key_ct" json:"auth_key_ct"`
	DeviceID      string             `db:"device_id" json:"device_id"`
	DeviceType    string             `db:"device_type" json:"device_type"`
	DeviceName    string             `db:"device_name" json:"device_name"`
	TotpRequired  bool               `db:"totp_required" json:"totp_required"`
	WebauthnState []byte             `db:"webauthn_state" json:"webauthn_state"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertMFAChallenge(ctx context.Context, arg InsertMFAChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMFAChallenge,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.AuthKeyCt,
		arg.DeviceID,
		arg.DeviceType,
		arg.DeviceName,
		arg.TotpRequired,
		arg.WebauthnState,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const takeMFAChallenge = `-- name: TakeMFAChallenge :one
DELETE FROM mfa_challenges
WHERE id = $1
RETURNING id, user_id, email, auth_key_ct, device_id, device_type, device_name, totp_required, webauthn_state, expires_at, failed_attempts
`

// Atomic SELECT-and-delete so two concurrent CompleteMFA calls cannot both
// claim the same challenge. The row is returned even if expired; the Go
// caller checks expires_at and surfaces ErrChallengeExpired.
func (q *Queries) TakeMFAChallenge(ctx context.Context, id uuid.UUID) (*models.MfaChallenge, error) {
	row := q.db.QueryRow(ctx, takeMFAChallenge, id)
	var i models.MfaChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.AuthKeyCt,
		&i.DeviceID,
		&i.DeviceType,
		&i.DeviceName,
		&i.TotpRequired,
		&i.WebauthnState,
		&i.ExpiresAt,
		&i.FailedAttempts,
	)
	return &i, err
}
