// Code generated by pgxgen. DO NOT EDIT.
package settings

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameSettings TableName = "settings"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameSettingsKey       ColumnName = "key"
	ColumnNameSettingsValue     ColumnName = "value"
	ColumnNameSettingsUpdatedAt ColumnName = "updated_at"
)

func SettingsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameSettingsKey,
		ColumnNameSettingsValue,
		ColumnNameSettingsUpdatedAt,
	}
}
