// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package settings

import (
	"context"

	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	Find(ctx context.Context) ([]*models.Setting, error)
	GetAllSettings(ctx context.Context) ([]*models.Setting, error)
	GetByKey(ctx context.Context, key string) (*models.Setting, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (*models.Setting, error)
}

var _ Querier = (*Queries)(nil)
