// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings_extra.sql

package settings

import (
	"context"

	"github.com/sxwebdev/oblivio/internal/models"
)

const getAllSettings = `-- name: GetAllSettings :many
SELECT key, value, updated_at FROM settings ORDER BY key
`

func (q *Queries) GetAllSettings(ctx context.Context) ([]*models.Setting, error) {
	rows, err := q.db.Query(ctx, getAllSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Setting{}
	for rows.Next() {
		var i models.Setting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = now()
RETURNING key, value, updated_at
`

type UpsertSettingParams struct {
	Key   string `db:"key" json:"key"`
	Value []byte `db:"value" json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (*models.Setting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.Key, arg.Value)
	var i models.Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return &i, err
}
