// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings_gen.sql

package settings

import (
	"context"

	"github.com/sxwebdev/oblivio/internal/models"
)

const find = `-- name: Find :many
SELECT key, value, updated_at FROM settings
`

func (q *Queries) Find(ctx context.Context) ([]*models.Setting, error) {
	rows, err := q.db.Query(ctx, find)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Setting{}
	for rows.Next() {
		var i models.Setting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByKey = `-- name: GetByKey :one
SELECT key, value, updated_at FROM settings WHERE key=$1 LIMIT 1
`

func (q *Queries) GetByKey(ctx context.Context, key string) (*models.Setting, error) {
	row := q.db.QueryRow(ctx, getByKey, key)
	var i models.Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return &i, err
}
