// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user_kdf_params

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	GetUserKDFParams(ctx context.Context, userID uuid.UUID) (*models.UserKdfParam, error)
	UpsertUserKDFParams(ctx context.Context, arg UpsertUserKDFParamsParams) error
}

var _ Querier = (*Queries)(nil)
