// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_kdf_params.sql

package user_kdf_params

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

const getUserKDFParams = `-- name: GetUserKDFParams :one
SELECT user_id, salt_user, argon2_t, argon2_m_kib, argon2_p, algo FROM user_kdf_params WHERE user_id = $1
`

func (q *Queries) GetUserKDFParams(ctx context.Context, userID uuid.UUID) (*models.UserKdfParam, error) {
	row := q.db.QueryRow(ctx, getUserKDFParams, userID)
	var i models.UserKdfParam
	err := row.Scan(
		&i.UserID,
		&i.SaltUser,
		&i.Argon2T,
		&i.Argon2MKib,
		&i.Argon2P,
		&i.Algo,
	)
	return &i, err
}

const upsertUserKDFParams = `-- name: UpsertUserKDFParams :exec
INSERT INTO user_kdf_params (user_id, salt_user, argon2_t, argon2_m_kib, argon2_p, algo)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE
SET salt_user    = EXCLUDED.salt_user,
    argon2_t     = EXCLUDED.argon2_t,
    argon2_m_kib = EXCLUDED.argon2_m_kib,
    argon2_p     = EXCLUDED.argon2_p,
    algo         = EXCLUDED.algo
`

type UpsertUserKDFParamsParams struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	SaltUser   []byte    `db:"salt_user" json:"salt_user"`
	Argon2T    int32     `db:"argon2_t" json:"argon2_t"`
	Argon2MKib int32     `db:"argon2_m_kib" json:"argon2_m_kib"`
	Argon2P    int32     `db:"argon2_p" json:"argon2_p"`
	Algo       string    `db:"algo" json:"algo"`
}

func (q *Queries) UpsertUserKDFParams(ctx context.Context, arg UpsertUserKDFParamsParams) error {
	_, err := q.db.Exec(ctx, upsertUserKDFParams,
		arg.UserID,
		arg.SaltUser,
		arg.Argon2T,
		arg.Argon2MKib,
		arg.Argon2P,
		arg.Algo,
	)
	return err
}
