// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package repo_email_verification_tokens

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :one
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING user_id
`

// Atomically marks the token consumed and returns its user_id. Returns
// pgx.ErrNoRows when the token is absent, expired or already used.
func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :execrows
DELETE FROM email_verification_tokens
WHERE expires_at <= now() AND (consumed_at IS NULL OR consumed_at <= now() - interval '7 days')
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailVerificationTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
INSERT INTO email_verification_tokens (token_hash, user_id, purpose, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertEmailVerificationTokenParams struct {
	TokenHash []byte             `db:"token_hash" json:"token_hash"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Purpose   string             `db:"purpose" json:"purpose"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerificationToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const invalidateActiveEmailVerificationTokens = `-- name: InvalidateActiveEmailVerificationTokens :execrows
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type InvalidateActiveEmailVerificationTokensParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Purpose string    `db:"purpose" json:"purpose"`
}

// Marks every still-active token for the user consumed. Run before
// generating a fresh ResendVerification token so an attacker can't keep
// exchange-stale links.
func (q *Queries) InvalidateActiveEmailVerificationTokens(ctx context.Context, arg InvalidateActiveEmailVerificationTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateActiveEmailVerificationTokens, arg.UserID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
