// Package middleware/idempotency dedupes mutating RPCs by Idempotency-Key.
//
// Implementation note: the middleware runs at the HTTP layer (not as a
// Connect interceptor) so it can stash and replay the exact serialized
// response bytes without having to know the proto response type.
//
// Storage is the Postgres `idempotency_keys` table with a 24h TTL. Replay
// returns the cached body verbatim, including content-type and status.
package middleware

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"errors"
	"io"
	"net/http"
	"net/textproto"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/sxwebdev/oblivio/internal/store"
	"github.com/sxwebdev/oblivio/internal/store/repos/repo_idempotency_keys"
)

const (
	idempotencyHeader = "Idempotency-Key"
	idempotencyTTL    = 24 * time.Hour
	maxReplayBody     = 1 << 20 // 1 MiB cap on cached response size
)

// IdempotencyConfig lists fully-qualified procedures that are
// idempotency-gated (typically every Create/Update/Delete RPC).
type IdempotencyConfig struct {
	Procedures map[string]struct{}
}

// IdempotencyMiddleware caches successful response bytes keyed by
// (user_id, Idempotency-Key) and replays them when the client retries.
//
// The middleware is applied AFTER the authn middleware so that it can
// extract user_id from the request context.
type IdempotencyMiddleware struct {
	store *store.Store
	cfg   IdempotencyConfig
}

// NewIdempotencyMiddleware constructs the middleware.
func NewIdempotencyMiddleware(st *store.Store, cfg IdempotencyConfig) *IdempotencyMiddleware {
	return &IdempotencyMiddleware{store: st, cfg: cfg}
}

// Wrap returns an http.Handler that applies idempotency around `next`.
func (m *IdempotencyMiddleware) Wrap(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		procedure := procedureFromPath(r.URL.Path)
		if _, gated := m.cfg.Procedures[procedure]; !gated {
			next.ServeHTTP(w, r)
			return
		}
		key := r.Header.Get(idempotencyHeader)
		if key == "" {
			next.ServeHTTP(w, r)
			return
		}
		uc, ok := FromContext(r.Context())
		if !ok {
			next.ServeHTTP(w, r)
			return
		}

		body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, maxReplayBody))
		if err != nil {
			http.Error(w, "request body too large", http.StatusRequestEntityTooLarge)
			return
		}
		_ = r.Body.Close()
		hash := sha256.Sum256(body)
		// Re-install body for the downstream handler.
		r.Body = io.NopCloser(bytes.NewReader(body))
		r.ContentLength = int64(len(body))

		repo := m.store.IdempotencyKeys()
		existing, err := repo.GetIdempotencyEntry(r.Context(), repo_idempotency_keys.GetIdempotencyEntryParams{
			UserID: uc.UserID,
			Key:    key,
		})
		if err != nil {
			if !errors.Is(err, pgx.ErrNoRows) {
				http.Error(w, "idempotency lookup failed", http.StatusInternalServerError)
				return
			}
			// sqlc-generated GetIdempotencyEntry returns (&zeroStruct, ErrNoRows)
			// on miss rather than (nil, ErrNoRows). Normalise so the downstream
			// nil-check actually distinguishes hit from miss.
			existing = nil
		}
		if existing != nil {
			if existing.Procedure != procedure {
				http.Error(w, "idempotency key reused on a different procedure", http.StatusConflict)
				return
			}
			if !bytes.Equal(existing.RequestHash, hash[:]) {
				http.Error(w, "idempotency key reused with different payload", http.StatusConflict)
				return
			}
			replay(w, r, existing.ResponseStatus, existing.ResponseBody)
			return
		}

		rec := &captureWriter{ResponseWriter: w, buf: &bytes.Buffer{}, max: maxReplayBody}
		next.ServeHTTP(rec, r)

		if rec.status < 200 || rec.status >= 300 {
			// Only cache 2xx responses; treat everything else as transient.
			return
		}
		if rec.truncated {
			return
		}
		framed := frameResponse(w.Header(), rec.buf.Bytes())
		if err := repo.InsertIdempotencyEntry(context.WithoutCancel(r.Context()), repo_idempotency_keys.InsertIdempotencyEntryParams{
			UserID:         uc.UserID,
			Key:            key,
			Procedure:      procedure,
			RequestHash:    hash[:],
			ResponseStatus: int32(rec.status),
			ResponseBody:   framed,
			ExpiresAt:      pgtype.Timestamptz{Time: time.Now().Add(idempotencyTTL), Valid: true},
		}); err != nil {
			// We've already shipped the response; failing to cache is not
			// fatal for the user. A retry will simply repeat the work.
			return
		}
	})
}

// replayHeaders lists the response headers we restore on a cached replay.
// Anything outside this list is regenerated by the http server (Date,
// Content-Length, transfer encoding…). Content-Encoding is critical:
// without it, a gzipped cached body shipped under a plain proto label
// arrives as garbage at the client and fails to decode.
var replayHeaders = []string{
	"Content-Type",
	"Content-Encoding",
}

// frameResponse packs the cached headers and body into the single
// `response_body` BYTEA column using HTTP wire syntax. This avoids a
// schema migration while preserving the response framing needed for a
// correct replay (notably Content-Encoding for compressed responses).
func frameResponse(h http.Header, body []byte) []byte {
	var buf bytes.Buffer
	for _, name := range replayHeaders {
		if v := h.Get(name); v != "" {
			buf.WriteString(name)
			buf.WriteString(": ")
			buf.WriteString(v)
			buf.WriteString("\r\n")
		}
	}
	buf.WriteString("\r\n")
	buf.Write(body)
	return buf.Bytes()
}

// unframeResponse is the inverse of frameResponse: returns headers and
// body suitable for replay. On parse failure (older cache entries that
// lack the header block) the input is treated as a raw body.
func unframeResponse(framed []byte) (http.Header, []byte) {
	tp := textproto.NewReader(bufio.NewReader(bytes.NewReader(framed)))
	mime, err := tp.ReadMIMEHeader()
	if err != nil {
		return nil, framed
	}
	// textproto consumed the headers + empty separator; the rest of the
	// underlying reader holds the body.
	rest, _ := io.ReadAll(tp.R)
	return http.Header(mime), rest
}

// procedureFromPath returns the request path unchanged. ConnectRPC's
// Spec.Procedure format already matches r.URL.Path for our routes (we
// don't mount a sub-prefix on the inner mux), so this exists only as a
// single point to extend if a future router prepends a prefix.
func procedureFromPath(p string) string { return p }

type captureWriter struct {
	http.ResponseWriter
	buf       *bytes.Buffer
	max       int
	status    int
	truncated bool
}

func (c *captureWriter) WriteHeader(code int) {
	if c.status == 0 {
		c.status = code
	}
	c.ResponseWriter.WriteHeader(code)
}

func (c *captureWriter) Write(p []byte) (int, error) {
	if c.status == 0 {
		c.status = http.StatusOK
	}
	if !c.truncated {
		remaining := c.max - c.buf.Len()
		if remaining > 0 {
			toCopy := len(p)
			if toCopy > remaining {
				toCopy = remaining
				c.truncated = true
			}
			c.buf.Write(p[:toCopy])
		} else {
			c.truncated = true
		}
	}
	return c.ResponseWriter.Write(p)
}

func replay(w http.ResponseWriter, r *http.Request, status int32, framed []byte) {
	cachedHeaders, body := unframeResponse(framed)
	for name, vals := range cachedHeaders {
		for _, v := range vals {
			w.Header().Add(name, v)
		}
	}
	if w.Header().Get("Content-Type") == "" {
		// Fallback for cache entries written before frameResponse existed.
		// Connect unary responses mirror the request's content-type.
		ct := r.Header.Get("Content-Type")
		if ct == "" {
			ct = "application/proto"
		}
		w.Header().Set("Content-Type", ct)
	}
	w.Header().Set("Content-Length", strconv.Itoa(len(body)))
	w.WriteHeader(int(status))
	_, _ = w.Write(body)
}
