// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package users

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

type Querier interface {
	CreateUser(ctx context.Context, email string) (*models.User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetUserByEmail(ctx context.Context, email string) (*models.User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
