/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VaultRouteImport } from "./routes/vault";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as EditorRouteImport } from "./routes/editor";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsAlertsRouteImport } from "./routes/settings.alerts";

const VaultRoute = VaultRouteImport.update({
  id: "/vault",
  path: "/vault",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const EditorRoute = EditorRouteImport.update({
  id: "/editor",
  path: "/editor",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAlertsRoute = SettingsAlertsRouteImport.update({
  id: "/settings/alerts",
  path: "/settings/alerts",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/editor": typeof EditorRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/search": typeof SearchRoute;
  "/vault": typeof VaultRoute;
  "/settings/alerts": typeof SettingsAlertsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/editor": typeof EditorRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/search": typeof SearchRoute;
  "/vault": typeof VaultRoute;
  "/settings/alerts": typeof SettingsAlertsRoute;
}
export interface FileRoutesById {
  "__root__": typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/editor": typeof EditorRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/search": typeof SearchRoute;
  "/vault": typeof VaultRoute;
  "/settings/alerts": typeof SettingsAlertsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/editor"
    | "/login"
    | "/register"
    | "/search"
    | "/vault"
    | "/settings/alerts";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/editor"
    | "/login"
    | "/register"
    | "/search"
    | "/vault"
    | "/settings/alerts";
  id:
    | "__root__"
    | "/"
    | "/editor"
    | "/login"
    | "/register"
    | "/search"
    | "/vault"
    | "/settings/alerts";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EditorRoute: typeof EditorRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  SearchRoute: typeof SearchRoute;
  VaultRoute: typeof VaultRoute;
  SettingsAlertsRoute: typeof SettingsAlertsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vault": {
      id: "/vault";
      path: "/vault";
      fullPath: "/vault";
      preLoaderRoute: typeof VaultRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/editor": {
      id: "/editor";
      path: "/editor";
      fullPath: "/editor";
      preLoaderRoute: typeof EditorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/alerts": {
      id: "/settings/alerts";
      path: "/settings/alerts";
      fullPath: "/settings/alerts";
      preLoaderRoute: typeof SettingsAlertsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  VaultRoute: VaultRoute,
  SettingsAlertsRoute: SettingsAlertsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
