// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_webauthn_credentials.sql

package repo_user_webauthn_credentials

import (
	"context"

	"github.com/google/uuid"
	"github.com/sxwebdev/oblivio/internal/models"
)

const clearAllWebAuthnUnlockBundles = `-- name: ClearAllWebAuthnUnlockBundles :exec
UPDATE user_webauthn_credentials
SET unlock_wrapped_vault_key = NULL,
    prf_salt                 = NULL
WHERE user_id = $1
  AND (unlock_wrapped_vault_key IS NOT NULL OR prf_salt IS NOT NULL)
`

func (q *Queries) ClearAllWebAuthnUnlockBundles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAllWebAuthnUnlockBundles, userID)
	return err
}

const clearWebAuthnUnlockBundle = `-- name: ClearWebAuthnUnlockBundle :exec
UPDATE user_webauthn_credentials
SET unlock_wrapped_vault_key = NULL,
    prf_salt                 = NULL
WHERE id = $1 AND user_id = $2
`

type ClearWebAuthnUnlockBundleParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ClearWebAuthnUnlockBundle(ctx context.Context, arg ClearWebAuthnUnlockBundleParams) error {
	_, err := q.db.Exec(ctx, clearWebAuthnUnlockBundle, arg.ID, arg.UserID)
	return err
}

const countWebAuthnCredentials = `-- name: CountWebAuthnCredentials :one
SELECT COUNT(*) FROM user_webauthn_credentials WHERE user_id = $1
`

func (q *Queries) CountWebAuthnCredentials(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebAuthnCredentials, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO user_webauthn_credentials (
    user_id, name, credential_id, public_key, aaguid, sign_count, transports, flags
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, credential_id, public_key, aaguid, sign_count, transports, created_at, last_used_at, flags, unlock_wrapped_vault_key, prf_salt
`

type CreateWebAuthnCredentialParams struct {
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	Name         string    `db:"name" json:"name"`
	CredentialID []byte    `db:"credential_id" json:"credential_id"`
	PublicKey    []byte    `db:"public_key" json:"public_key"`
	Aaguid       []byte    `db:"aaguid" json:"aaguid"`
	SignCount    int64     `db:"sign_count" json:"sign_count"`
	Transports   []string  `db:"transports" json:"transports"`
	Flags        int16     `db:"flags" json:"flags"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (*models.UserWebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.Name,
		arg.CredentialID,
		arg.PublicKey,
		arg.Aaguid,
		arg.SignCount,
		arg.Transports,
		arg.Flags,
	)
	var i models.UserWebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.SignCount,
		&i.Transports,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Flags,
		&i.UnlockWrappedVaultKey,
		&i.PrfSalt,
	)
	return &i, err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM user_webauthn_credentials
WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	return err
}

const getWebAuthnCredentialByCredID = `-- name: GetWebAuthnCredentialByCredID :one
SELECT id, user_id, name, credential_id, public_key, aaguid, sign_count, transports, created_at, last_used_at, flags, unlock_wrapped_vault_key, prf_salt FROM user_webauthn_credentials WHERE credential_id = $1
`

func (q *Queries) GetWebAuthnCredentialByCredID(ctx context.Context, credentialID []byte) (*models.UserWebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByCredID, credentialID)
	var i models.UserWebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.SignCount,
		&i.Transports,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Flags,
		&i.UnlockWrappedVaultKey,
		&i.PrfSalt,
	)
	return &i, err
}

const getWebAuthnCredentialByID = `-- name: GetWebAuthnCredentialByID :one
SELECT id, user_id, name, credential_id, public_key, aaguid, sign_count, transports, created_at, last_used_at, flags, unlock_wrapped_vault_key, prf_salt FROM user_webauthn_credentials
WHERE id = $1 AND user_id = $2
`

type GetWebAuthnCredentialByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetWebAuthnCredentialByID(ctx context.Context, arg GetWebAuthnCredentialByIDParams) (*models.UserWebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByID, arg.ID, arg.UserID)
	var i models.UserWebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.SignCount,
		&i.Transports,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Flags,
		&i.UnlockWrappedVaultKey,
		&i.PrfSalt,
	)
	return &i, err
}

const listWebAuthnCredentials = `-- name: ListWebAuthnCredentials :many
SELECT id, user_id, name, credential_id, public_key, aaguid, sign_count, transports, created_at, last_used_at, flags, unlock_wrapped_vault_key, prf_salt FROM user_webauthn_credentials
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebAuthnCredentials(ctx context.Context, userID uuid.UUID) ([]*models.UserWebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.UserWebauthnCredential{}
	for rows.Next() {
		var i models.UserWebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CredentialID,
			&i.PublicKey,
			&i.Aaguid,
			&i.SignCount,
			&i.Transports,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Flags,
			&i.UnlockWrappedVaultKey,
			&i.PrfSalt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWebAuthnUnlockBundle = `-- name: SetWebAuthnUnlockBundle :exec
UPDATE user_webauthn_credentials
SET unlock_wrapped_vault_key = $3,
    prf_salt                 = $4
WHERE id = $1 AND user_id = $2
`

type SetWebAuthnUnlockBundleParams struct {
	ID                    uuid.UUID `db:"id" json:"id"`
	UserID                uuid.UUID `db:"user_id" json:"user_id"`
	UnlockWrappedVaultKey []byte    `db:"unlock_wrapped_vault_key" json:"unlock_wrapped_vault_key"`
	PrfSalt               []byte    `db:"prf_salt" json:"prf_salt"`
}

func (q *Queries) SetWebAuthnUnlockBundle(ctx context.Context, arg SetWebAuthnUnlockBundleParams) error {
	_, err := q.db.Exec(ctx, setWebAuthnUnlockBundle,
		arg.ID,
		arg.UserID,
		arg.UnlockWrappedVaultKey,
		arg.PrfSalt,
	)
	return err
}

const touchWebAuthnCredential = `-- name: TouchWebAuthnCredential :exec
UPDATE user_webauthn_credentials
SET sign_count   = $2,
    flags        = $3,
    last_used_at = now()
WHERE id = $1
`

type TouchWebAuthnCredentialParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SignCount int64     `db:"sign_count" json:"sign_count"`
	Flags     int16     `db:"flags" json:"flags"`
}

func (q *Queries) TouchWebAuthnCredential(ctx context.Context, arg TouchWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, touchWebAuthnCredential, arg.ID, arg.SignCount, arg.Flags)
	return err
}
