// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package repo_audit_log

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const appendAuditEntry = `-- name: AppendAuditEntry :one
INSERT INTO audit_log (
    user_id, action, target_id, ip, user_agent, metadata, prev_hash, self_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, action, target_id, ip, user_agent, metadata, prev_hash, self_hash, created_at
`

type AppendAuditEntryParams struct {
	UserID    uuid.NullUUID      `db:"user_id" json:"user_id"`
	Action    models.AuditAction `db:"action" json:"action"`
	TargetID  uuid.NullUUID      `db:"target_id" json:"target_id"`
	Ip        *netip.Addr        `db:"ip" json:"ip"`
	UserAgent pgtype.Text        `db:"user_agent" json:"user_agent"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	PrevHash  []byte             `db:"prev_hash" json:"prev_hash"`
	SelfHash  []byte             `db:"self_hash" json:"self_hash"`
}

func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (*models.AuditLog, error) {
	row := q.db.QueryRow(ctx, appendAuditEntry,
		arg.UserID,
		arg.Action,
		arg.TargetID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
		arg.PrevHash,
		arg.SelfHash,
	)
	var i models.AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.TargetID,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
		&i.PrevHash,
		&i.SelfHash,
		&i.CreatedAt,
	)
	return &i, err
}

const getAuditByID = `-- name: GetAuditByID :one
SELECT id, user_id, action, target_id, ip, user_agent, metadata, prev_hash, self_hash, created_at FROM audit_log WHERE id = $1
`

func (q *Queries) GetAuditByID(ctx context.Context, id int64) (*models.AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditByID, id)
	var i models.AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.TargetID,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
		&i.PrevHash,
		&i.SelfHash,
		&i.CreatedAt,
	)
	return &i, err
}

const getAuditChainHead = `-- name: GetAuditChainHead :one
SELECT id, self_hash FROM audit_log ORDER BY id DESC LIMIT 1
`

type GetAuditChainHeadRow struct {
	ID       int64  `db:"id" json:"id"`
	SelfHash []byte `db:"self_hash" json:"self_hash"`
}

func (q *Queries) GetAuditChainHead(ctx context.Context) (*GetAuditChainHeadRow, error) {
	row := q.db.QueryRow(ctx, getAuditChainHead)
	var i GetAuditChainHeadRow
	err := row.Scan(&i.ID, &i.SelfHash)
	return &i, err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, user_id, action, target_id, ip, user_agent, metadata, prev_hash, self_hash, created_at
FROM audit_log
WHERE user_id = $1
  AND ($2::audit_action IS NULL OR action = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz   IS NULL OR created_at <= $4)
  AND ($5::bigint      IS NULL OR id < $5)
ORDER BY id DESC
LIMIT $6
`

type ListAuditEntriesParams struct {
	UserID       uuid.NullUUID          `db:"user_id" json:"user_id"`
	ActionFilter models.NullAuditAction `db:"action_filter" json:"action_filter"`
	FromTime     pgtype.Timestamptz     `db:"from_time" json:"from_time"`
	ToTime       pgtype.Timestamptz     `db:"to_time" json:"to_time"`
	CursorID     pgtype.Int8            `db:"cursor_id" json:"cursor_id"`
	PageLimit    int32                  `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]*models.AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries,
		arg.UserID,
		arg.ActionFilter,
		arg.FromTime,
		arg.ToTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.AuditLog{}
	for rows.Next() {
		var i models.AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.TargetID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.PrevHash,
			&i.SelfHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditFromID = `-- name: ListAuditFromID :many
SELECT id, user_id, action, target_id, ip, user_agent, metadata, prev_hash, self_hash, created_at FROM audit_log WHERE id > $1 ORDER BY id ASC LIMIT $2
`

type ListAuditFromIDParams struct {
	ID    int64 `db:"id" json:"id"`
	Limit int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListAuditFromID(ctx context.Context, arg ListAuditFromIDParams) ([]*models.AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditFromID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.AuditLog{}
	for rows.Next() {
		var i models.AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.TargetID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.PrevHash,
			&i.SelfHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
