// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package repo_entries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sxwebdev/oblivio/internal/models"
)

const countEntriesByProject = `-- name: CountEntriesByProject :one
SELECT count(*) FROM entries
WHERE user_id = $1 AND project_id = $2
`

type CountEntriesByProjectParams struct {
	UserID    uuid.UUID     `db:"user_id" json:"user_id"`
	ProjectID uuid.NullUUID `db:"project_id" json:"project_id"`
}

func (q *Queries) CountEntriesByProject(ctx context.Context, arg CountEntriesByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntriesByProject, arg.UserID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    id, user_id, project_id, kind, encrypted_blob, wrapped_item_key,
    title_hash, domain_hash, has_totp, is_favorite
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, project_id, kind, encrypted_blob, wrapped_item_key, title_hash, domain_hash, has_totp, is_favorite, version, created_at, updated_at
`

type CreateEntryParams struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	UserID         uuid.UUID        `db:"user_id" json:"user_id"`
	ProjectID      uuid.NullUUID    `db:"project_id" json:"project_id"`
	Kind           models.EntryKind `db:"kind" json:"kind"`
	EncryptedBlob  []byte           `db:"encrypted_blob" json:"encrypted_blob"`
	WrappedItemKey []byte           `db:"wrapped_item_key" json:"wrapped_item_key"`
	TitleHash      []byte           `db:"title_hash" json:"title_hash"`
	DomainHash     []byte           `db:"domain_hash" json:"domain_hash"`
	HasTotp        bool             `db:"has_totp" json:"has_totp"`
	IsFavorite     bool             `db:"is_favorite" json:"is_favorite"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (*models.Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Kind,
		arg.EncryptedBlob,
		arg.WrappedItemKey,
		arg.TitleHash,
		arg.DomainHash,
		arg.HasTotp,
		arg.IsFavorite,
	)
	var i models.Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.EncryptedBlob,
		&i.WrappedItemKey,
		&i.TitleHash,
		&i.DomainHash,
		&i.HasTotp,
		&i.IsFavorite,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM entries
WHERE id = $1 AND user_id = $2
`

type DeleteEntryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEntriesByIDs = `-- name: GetEntriesByIDs :many
SELECT id, user_id, project_id, kind, encrypted_blob, wrapped_item_key, title_hash, domain_hash, has_totp, is_favorite, version, created_at, updated_at FROM entries
WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type GetEntriesByIDsParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Ids    []uuid.UUID `db:"ids" json:"ids"`
}

func (q *Queries) GetEntriesByIDs(ctx context.Context, arg GetEntriesByIDsParams) ([]*models.Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Entry{}
	for rows.Next() {
		var i models.Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Kind,
			&i.EncryptedBlob,
			&i.WrappedItemKey,
			&i.TitleHash,
			&i.DomainHash,
			&i.HasTotp,
			&i.IsFavorite,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, project_id, kind, encrypted_blob, wrapped_item_key, title_hash, domain_hash, has_totp, is_favorite, version, created_at, updated_at FROM entries
WHERE id = $1 AND user_id = $2
`

type GetEntryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (*models.Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.ID, arg.UserID)
	var i models.Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.EncryptedBlob,
		&i.WrappedItemKey,
		&i.TitleHash,
		&i.DomainHash,
		&i.HasTotp,
		&i.IsFavorite,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, user_id, project_id, kind, encrypted_blob, wrapped_item_key, title_hash, domain_hash, has_totp, is_favorite, version, created_at, updated_at
FROM entries
WHERE user_id = $1
  AND ($2::uuid     IS NULL OR project_id = $2)
  AND ($3::entry_kind     IS NULL OR kind = $3)
  AND ($4::bytea[] IS NULL OR title_hash = ANY($4::bytea[]))
  AND ($5::bytea[] IS NULL OR domain_hash = ANY($5::bytea[]))
  AND ($6::bool IS NULL OR is_favorite = $6)
  AND ($7::bool  IS NULL OR has_totp    = $7)
  AND ($8::timestamptz IS NULL OR updated_at > $8)
ORDER BY updated_at DESC, id DESC
LIMIT $9
`

type ListEntriesParams struct {
	UserID        uuid.UUID            `db:"user_id" json:"user_id"`
	ProjectID     uuid.NullUUID        `db:"project_id" json:"project_id"`
	Kind          models.NullEntryKind `db:"kind" json:"kind"`
	TitleHashes   [][]byte             `db:"title_hashes" json:"title_hashes"`
	DomainHashes  [][]byte             `db:"domain_hashes" json:"domain_hashes"`
	FavoritesOnly pgtype.Bool          `db:"favorites_only" json:"favorites_only"`
	HasTotpOnly   pgtype.Bool          `db:"has_totp_only" json:"has_totp_only"`
	UpdatedAfter  pgtype.Timestamptz   `db:"updated_after" json:"updated_after"`
	PageLimit     int32                `db:"page_limit" json:"page_limit"`
}

// Filters: project_id (NULLable; pass NULL to match all), kind, title_hashes,
// domain_hashes, favorites_only, has_totp, updated_after. Pagination with
// cursor (updated_at, id) ordering DESC by updated_at.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]*models.Entry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.UserID,
		arg.ProjectID,
		arg.Kind,
		arg.TitleHashes,
		arg.DomainHashes,
		arg.FavoritesOnly,
		arg.HasTotpOnly,
		arg.UpdatedAfter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Entry{}
	for rows.Next() {
		var i models.Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Kind,
			&i.EncryptedBlob,
			&i.WrappedItemKey,
			&i.TitleHash,
			&i.DomainHash,
			&i.HasTotp,
			&i.IsFavorite,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleFavorite = `-- name: ToggleFavorite :one
UPDATE entries SET is_favorite = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, project_id, kind, encrypted_blob, wrapped_item_key, title_hash, domain_hash, has_totp, is_favorite, version, created_at, updated_at
`

type ToggleFavoriteParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	IsFavorite bool      `db:"is_favorite" json:"is_favorite"`
}

func (q *Queries) ToggleFavorite(ctx context.Context, arg ToggleFavoriteParams) (*models.Entry, error) {
	row := q.db.QueryRow(ctx, toggleFavorite, arg.ID, arg.UserID, arg.IsFavorite)
	var i models.Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.EncryptedBlob,
		&i.WrappedItemKey,
		&i.TitleHash,
		&i.DomainHash,
		&i.HasTotp,
		&i.IsFavorite,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET project_id       = $3,
    kind             = $4,
    encrypted_blob   = $5,
    wrapped_item_key = $6,
    title_hash       = $7,
    domain_hash      = $8,
    has_totp         = $9,
    is_favorite      = $10,
    version          = version + 1,
    updated_at       = now()
WHERE id = $1 AND user_id = $2 AND version = $11
RETURNING id, user_id, project_id, kind, encrypted_blob, wrapped_item_key, title_hash, domain_hash, has_totp, is_favorite, version, created_at, updated_at
`

type UpdateEntryParams struct {
	ID              uuid.UUID        `db:"id" json:"id"`
	UserID          uuid.UUID        `db:"user_id" json:"user_id"`
	ProjectID       uuid.NullUUID    `db:"project_id" json:"project_id"`
	Kind            models.EntryKind `db:"kind" json:"kind"`
	EncryptedBlob   []byte           `db:"encrypted_blob" json:"encrypted_blob"`
	WrappedItemKey  []byte           `db:"wrapped_item_key" json:"wrapped_item_key"`
	TitleHash       []byte           `db:"title_hash" json:"title_hash"`
	DomainHash      []byte           `db:"domain_hash" json:"domain_hash"`
	HasTotp         bool             `db:"has_totp" json:"has_totp"`
	IsFavorite      bool             `db:"is_favorite" json:"is_favorite"`
	ExpectedVersion int32            `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (*models.Entry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Kind,
		arg.EncryptedBlob,
		arg.WrappedItemKey,
		arg.TitleHash,
		arg.DomainHash,
		arg.HasTotp,
		arg.IsFavorite,
		arg.ExpectedVersion,
	)
	var i models.Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.EncryptedBlob,
		&i.WrappedItemKey,
		&i.TitleHash,
		&i.DomainHash,
		&i.HasTotp,
		&i.IsFavorite,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
